/* Graphinator — ExtendScript chart builder.
 *
 * Called from the CEP panel via evalScript. Builds animated bar / line / pie
 * charts as native shape + text layers in the active comp.
 *
 * The hybrid contract:
 *   - The PANEL owns the data, chart type and number formatting. Pressing
 *     Update deletes every layer tagged GRAPHINATOR_ITEM and rebuilds it.
 *   - The ">> GRAPH CONTROLLER <<" null owns colors, animation timing and
 *     scale as LIVE effect controls; every generated layer derives from it
 *     via expressions. On Update the controller (and any tweaks made to it)
 *     is preserved — only its data blob and build markers are refreshed.
 *
 * Geometry is authored for a 1920x1080 comp (chart ≈ 75% of frame, wider
 * than tall for bar/line) and scaled proportionally for other comp sizes.
 */

(function (global) {

  // ------------------------------ FONT CONFIG ------------------------------
  // Default typeface for all chart text. If your font shows a different
  // family name in AE's Character panel, edit FONT_FAMILY here. Styles are
  // matched per weight from the candidate lists (first installed style
  // wins); Arial is the fallback when the family or AE's font API (24+)
  // is unavailable.
  var FONT_FAMILY = "Arthouse Owned";
  var FONT_STYLE_CANDIDATES = {
    regular: ["Regular", "Book", "Light", "Medium"],
    medium:  ["Medium", "Regular", "Book"],
    bold:    ["Bold", "Heavy", "Semibold", "SemiBold", "Demibold", "Black", "Medium"]
  };
  var FONT_FALLBACK_PS = { regular: "ArialMT", medium: "ArialMT", bold: "Arial-BoldMT" };
  // --------------------------------------------------------------------------

  var CTRL_NAME = ">> GRAPH CONTROLLER <<";

  // Timeline label colors — one per layer type so the stack reads at a
  // glance. (AE label indices: 1 Red, 2 Yellow, 3 Aqua, 4 Pink, 6 Peach,
  // 7 Sea Foam, 8 Blue, 9 Green, 10 Purple, 12 Brown, 15 Sandstone.)
  var LC = {
    controller: 10, // purple
    title: 1,       // red
    legend: 9,      // green
    value: 2,       // yellow — count-up value labels
    category: 6,    // peach — category names / pie names
    tick: 15,       // sandstone — muted axis ticks
    axes: 12,       // brown — axes & gridlines
    bar: 8,         // blue — bar shapes
    line: 8,        // blue — the chart line
    area: 7,        // sea foam — area fill
    dot: 4,         // pink — line points
    slice: 8,       // blue — pie slices
    ring: 12,       // brown — pie outline ring
    leader: 3       // aqua — pie leader lines
  };
  var ITEM_TAG = "GRAPHINATOR_ITEM";
  var CTRL_TAG = "GRAPHINATOR_CONTROLLER";
  var DATA_TAG = "@@GRAPHINATOR_DATA@@";

  var ITEM_COMMENT = ITEM_TAG + " — generated by the Graphinator panel. Manual edits to this layer are lost on Update.";

  var EASING_INDEX = { linear: 1, smooth: 2, overshoot: 3, bounce: 4 };

  // ================================================================ utils

  function parseJSON(text) {
    // Crockford-style validation, then eval (ExtendScript has no native JSON).
    var t = String(text);
    var cleaned = t
      .replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g, "@")
      .replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g, "]")
      .replace(/(?:^|:|,)(?:\s*\[)+/g, "");
    if (!/^[\],:{}\s]*$/.test(cleaned)) {
      throw new Error("Invalid config payload.");
    }
    return eval("(" + t + ")");
  }

  function escStr(s) {
    return String(s).replace(/\\/g, "\\\\").replace(/"/g, "\\\"");
  }

  function pad2(n) { return (n < 10 ? "0" : "") + n; }

  function hexToRgb(hex) {
    var h = String(hex).replace("#", "");
    if (h.length === 3) {
      h = h.charAt(0) + h.charAt(0) + h.charAt(1) + h.charAt(1) + h.charAt(2) + h.charAt(2);
    }
    return [
      parseInt(h.substr(0, 2), 16) / 255,
      parseInt(h.substr(2, 2), 16) / 255,
      parseInt(h.substr(4, 2), 16) / 255
    ];
  }

  function round3(v) { return Math.round(v * 1000) / 1000; }

  // Pie angles need more precision — adjacent wedges share exact boundaries.
  function round6(v) { return Math.round(v * 1000000) / 1000000; }

  function thousandsStr(s) {
    var pt = String(s).split(".");
    var x = pt[0];
    var neg = x.charAt(0) === "-";
    if (neg) x = x.substr(1);
    var r = "";
    var c = 0;
    for (var i = x.length - 1; i >= 0; i--) {
      r = x.charAt(i) + r;
      c++;
      if (c % 3 === 0 && i > 0) r = "," + r;
    }
    return (neg ? "-" : "") + r + (pt.length > 1 ? "." + pt[1] : "");
  }

  // Static (non-animated) number formatting for axis ticks etc.
  function formatStatic(v, fmt, total) {
    if (fmt.mode === "percent") {
      return (total > 0 ? (v / total * 100) : 0).toFixed(1) + "%";
    }
    var s = v.toFixed(fmt.decimals);
    if (fmt.thousands) s = thousandsStr(s);
    return (fmt.prefix || "") + s + (fmt.suffix || "");
  }

  function niceStep(range, targetTicks) {
    if (range <= 0) return 1;
    var raw = range / targetTicks;
    var mag = Math.pow(10, Math.floor(Math.log(raw) / Math.LN10));
    var norm = raw / mag;
    var step;
    if (norm < 1.5) step = 1;
    else if (norm < 3) step = 2;
    else if (norm < 7) step = 5;
    else step = 10;
    return step * mag;
  }

  // ====================================================== expression text

  /* Shared timing preamble. Defines p (raw 0..1 progress for item `index`,
   * staggered) and e (eased progress; may exceed 1 for Overshoot). */
  function preamble(index) {
    return 'var C=thisComp.layer("' + CTRL_NAME + '");\n' +
      'var dur=Math.max(C.effect("ANIM | Build Duration")(1),0.01);\n' +
      'var stag=C.effect("ANIM | Stagger")(1);\n' +
      'var dly=C.effect("ANIM | Start Delay")(1);\n' +
      'var sty=Math.round(C.effect("ANIM | Easing Style")(1));\n' +
      'function easeP(q){\n' +
      ' if(sty<=1)return q;\n' +
      ' if(sty==2)return q*q*(3-2*q);\n' +
      ' if(sty==3){var s=1.70158,u=q-1;return 1+(s+1)*u*u*u+s*u*u;}\n' +
      ' var n1=7.5625,d1=2.75,u=q;\n' +
      ' if(u<1/d1)return n1*u*u;\n' +
      ' if(u<2/d1){u-=1.5/d1;return n1*u*u+0.75;}\n' +
      ' if(u<2.5/d1){u-=2.25/d1;return n1*u*u+0.9375;}\n' +
      ' u-=2.625/d1;return n1*u*u+0.984375;\n' +
      '}\n' +
      'var p=clamp((time-inPoint-dly-' + index + '*stag)/dur,0,1);\n' +
      'var e=easeP(p);\n';
  }

  /* Live color ramp: derive this item's tone from the master color.
   * t is the baked tone offset (-0.5..0.5); mult darkens (outlines). */
  function rampColorExpr(t, mult) {
    return 'var C=thisComp.layer("' + CTRL_NAME + '");\n' +
      'var mc=C.effect("COLOR | Master Color")(1);\n' +
      'var sp=C.effect("COLOR | Tone Spread")(1)/100;\n' +
      'var h=rgbToHsl(mc);\n' +
      'var t=' + round3(t) + ';\n' +
      'var l=clamp(h[2]+t*sp*0.7,0.08,0.94)*' + mult + ';\n' +
      'var s=clamp(h[1]-t*sp*0.25,0.05,1);\n' +
      'hslToRgb([h[0],s,clamp(l,0,1),1])';
  }

  function labelColorExpr() {
    return 'thisComp.layer("' + CTRL_NAME + '").effect("STYLE | Label Color")(1)';
  }

  function outlineWidthExpr() {
    return 'thisComp.layer("' + CTRL_NAME + '").effect("STYLE | Outline Width")(1)';
  }

  var THS_FN =
    'function ths(str){var pt=(""+str).split(".");var x=pt[0];var ng=x.charAt(0)=="-";' +
    'if(ng)x=x.substr(1);var r="";var c=0;for(var i=x.length-1;i>=0;i--){r=x.charAt(i)+r;c++;' +
    'if(c%3==0&&i>0)r=","+r;}return (ng?"-":"")+r+(pt.length>1?"."+pt[1]:"");}\n';

  /* Count-up label body: uses `e` from the preamble, emits `out`. */
  function countUpBody(value, total, fmt, progressVar) {
    var pv = progressVar || "e";
    if (fmt.mode === "percent") {
      var share = total > 0 ? (value / total * 100) : 0;
      return 'var out=(' + round3(share) + '*' + pv + ').toFixed(1)+"%";\n';
    }
    var core = 'v.toFixed(' + fmt.decimals + ')';
    if (fmt.thousands) core = 'ths(' + core + ')';
    return THS_FN +
      'var v=' + round3(value) + '*' + pv + ';\n' +
      'var out="' + escStr(fmt.prefix || "") + '"+' + core + '+"' + escStr(fmt.suffix || "") + '";\n';
  }

  // ======================================================== layer helpers

  function getComp() {
    var comp = app.project.activeItem;
    if (!(comp && comp instanceof CompItem)) {
      comp = app.project.items.addComp("Graphinator Chart", 1920, 1080, 1.0, 10, 29.97);
      comp.openInViewer();
    }
    return comp;
  }

  function findController(comp) {
    for (var i = 1; i <= comp.numLayers; i++) {
      var lay = comp.layer(i);
      if (lay.name === CTRL_NAME && String(lay.comment).indexOf(CTRL_TAG) === 0) return lay;
      if (lay.name === CTRL_NAME) return lay; // renamed comment, still ours
    }
    return null;
  }

  function removeItems(comp) {
    for (var i = comp.numLayers; i >= 1; i--) {
      var lay = comp.layer(i);
      if (String(lay.comment).indexOf(ITEM_TAG) === 0) {
        lay.locked = false;
        lay.remove();
      }
    }
  }

  function fxParade(layer) {
    return layer.property("ADBE Effect Parade");
  }

  /* Add an effect control if it doesn't exist yet. Returns the effect and
   * whether it was just created (so panel defaults only seed new controls). */
  function ensureFx(layer, matchName, dispName, defVal) {
    var parade = fxParade(layer);
    var existing = null;
    try { existing = parade.property(dispName); } catch (e) { existing = null; }
    if (existing) return { fx: existing, created: false };
    var fx = parade.addProperty(matchName);
    fx.name = dispName;
    if (defVal !== null && defVal !== undefined) fx.property(1).setValue(defVal);
    return { fx: fx, created: true };
  }

  function ensureEasingFx(layer, defIndex) {
    var parade = fxParade(layer);
    var existing = null;
    try { existing = parade.property("ANIM | Easing Style"); } catch (e) { existing = null; }
    if (existing) return;
    try {
      var dd = parade.addProperty("ADBE Dropdown Control");
      // setPropertyParameters invalidates references; use what it returns.
      var menu = dd.property(1).setPropertyParameters(["Linear", "Smooth", "Overshoot", "Bounce"]);
      var eff = menu.propertyGroup(1);
      eff.name = "ANIM | Easing Style";
      eff.property(1).setValue(defIndex);
    } catch (err) {
      // Older AE without scriptable dropdowns — fall back to a slider.
      var sl = parade.addProperty("ADBE Slider Control");
      sl.name = "ANIM | Easing Style";
      sl.property(1).setValue(defIndex);
    }
  }

  function ensureController(comp, cfg) {
    var ctrl = findController(comp);
    var isNew = false;
    if (!ctrl) {
      ctrl = comp.layers.addNull(comp.duration);
      ctrl.name = CTRL_NAME;
      ctrl.anchorPoint.setValue([0, 0]);
      ctrl.position.setValue([comp.width / 2, comp.height / 2]);
      ctrl.label = 10; // purple — stands out in the timeline
      isNew = true;
    }

    var master = hexToRgb(cfg.color.master);
    var defs = [
      ["ADBE Color Control", "COLOR | Master Color", [master[0], master[1], master[2], 1]],
      ["ADBE Slider Control", "COLOR | Tone Spread", cfg.color.spread],
      ["ADBE Slider Control", "ANIM | Start Delay", cfg.anim.delay],
      ["ADBE Slider Control", "ANIM | Build Duration", cfg.anim.duration],
      ["ADBE Slider Control", "ANIM | Stagger", cfg.anim.stagger],
      ["ADBE Slider Control", "STYLE | Outline Width", 4],
      ["ADBE Slider Control", "STYLE | Line Weight", 8],
      ["ADBE Checkbox Control", "STYLE | Glow Enabled", 1],
      ["ADBE Slider Control", "STYLE | Glow Intensity", 0.35],
      ["ADBE Color Control", "STYLE | Label Color", [0.95, 0.95, 0.95, 1]],
      ["ADBE Slider Control", "SCALE | Overall Scale", 100]
    ];
    for (var i = 0; i < defs.length; i++) {
      ensureFx(ctrl, defs[i][0], defs[i][1], defs[i][2]);
    }
    ensureEasingFx(ctrl, EASING_INDEX[cfg.anim.easing] || 2);

    // Whole chart scales about the comp center from one slider.
    ctrl.scale.expression =
      'var s=effect("SCALE | Overall Scale")(1);\n[s,s]';

    return { ctrl: ctrl, isNew: isNew };
  }

  function readAnimValues(ctrl, cfg) {
    // Live values win over panel values so Update respects controller tweaks.
    var a = { delay: cfg.anim.delay, duration: cfg.anim.duration, stagger: cfg.anim.stagger };
    try { a.delay = ctrl.property("ADBE Effect Parade").property("ANIM | Start Delay").property(1).value; } catch (e1) {}
    try { a.duration = ctrl.property("ADBE Effect Parade").property("ANIM | Build Duration").property(1).value; } catch (e2) {}
    try { a.stagger = ctrl.property("ADBE Effect Parade").property("ANIM | Stagger").property(1).value; } catch (e3) {}
    return a;
  }

  function setMarkers(ctrl, startT, endT) {
    var mp = ctrl.property("ADBE Marker");
    while (mp.numKeys > 0) mp.removeKey(1);
    mp.setValueAtTime(startT, new MarkerValue("BUILD START — timing is live in this layer's ANIM effects. Markers refresh on Update."));
    mp.setValueAtTime(endT, new MarkerValue("BUILD COMPLETE"));
  }

  function storeData(ctrl, jsonStr) {
    ctrl.comment =
      CTRL_TAG + "\n" +
      "— Colors, timing, outline & scale: LIVE here (select me > Effect Controls).\n" +
      "— Data, chart type & formatting: Window > Extensions > Graphinator, then Update.\n" +
      "— Manual edits to generated layers are lost on Update.\n" +
      DATA_TAG + jsonStr;
  }

  function tagItem(layer, ctrl) {
    layer.comment = ITEM_COMMENT;
    layer.setParentWithJump(ctrl);
  }

  function addShapeItem(comp, ctrl, name, labelColor) {
    var lay = comp.layers.addShape();
    lay.name = name;
    if (labelColor) { try { lay.label = labelColor; } catch (eL) {} }
    tagItem(lay, ctrl);
    return lay;
  }

  /* Resolve the configured family's PostScript names per weight via the
   * font API (AE 24+). boldIsFaux flags a family with no real bold style,
   * so bold text can fall back to synthetic bold. */
  var CHART_FONTS = null;

  function resolveFonts() {
    var out = { boldIsFaux: false };
    var weights = ["regular", "medium", "bold"];
    for (var i = 0; i < weights.length; i++) {
      var w = weights[i];
      var ps = null;
      var chosenStyle = null;
      try {
        var cands = FONT_STYLE_CANDIDATES[w];
        for (var j = 0; j < cands.length && !ps; j++) {
          var arr = app.fonts.getFontsByFamilyNameAndStyleName(FONT_FAMILY, cands[j]);
          if (arr && arr.length > 0) { ps = arr[0].postScriptName; chosenStyle = cands[j]; }
        }
      } catch (e) { ps = null; }
      if (w === "bold" && ps && chosenStyle === "Medium") out.boldIsFaux = true;
      out[w] = ps || FONT_FALLBACK_PS[w];
    }
    return out;
  }

  function addTextItem(comp, ctrl, name, str, fontSize, justification, weight, labelColor) {
    var lay = comp.layers.addText(str);
    lay.name = name;
    if (labelColor) { try { lay.label = labelColor; } catch (eL) {} }
    var tp = lay.property("ADBE Text Properties").property("ADBE Text Document");
    var td = tp.value;
    td.fontSize = fontSize;
    var w = weight || "medium";
    try { td.font = CHART_FONTS[w]; } catch (eFont) {}
    if (w === "bold" && CHART_FONTS.boldIsFaux) {
      try { td.fauxBold = true; } catch (eFaux) {}
    }
    td.applyFill = true;
    td.fillColor = [0.95, 0.95, 0.95];
    td.applyStroke = false;
    td.justification = justification;
    tp.setValue(td);
    tagItem(lay, ctrl);
    addLabelColorFx(lay);
    return lay;
  }

  function findFxProp(fx, matchName, dispName) {
    var p = null;
    try { p = fx.property(matchName); } catch (e1) { p = null; }
    if (!p) { try { p = fx.property(dispName); } catch (e2) { p = null; } }
    return p;
  }

  function setFxValue(fx, m, d, v) { var p = findFxProp(fx, m, d); if (p) { try { p.setValue(v); } catch (e) {} } }
  function setFxExpr(fx, m, d, ex) { var p = findFxProp(fx, m, d); if (p) { try { p.expression = ex; } catch (e) {} } }

  function applyColorSafe(prop, spec) {
    try { applyColor(prop, spec); } catch (e) {}
  }

  /* ---- Pro glow stack ----------------------------------------------------
   * AE's single Glow is weak, so stack three: tight core, medium spread,
   * wide fall-off — all in Add mode with A & B colors derived from the
   * item's tone. Every tier is gated by STYLE | Glow Enabled and scaled by
   * STYLE | Glow Intensity on the controller, so the whole stack switches
   * off with one checkbox. */
  function glowIntensityExpr(base) {
    return 'var C=thisComp.layer("' + CTRL_NAME + '");\n' +
      'var on=C.effect("STYLE | Glow Enabled")(1);\n' +
      'var m=Math.max(C.effect("STYLE | Glow Intensity")(1),0);\n' +
      'on>0?' + base + '*m:0';
  }

  function addOneGlow(layer, name, threshold, radius, baseIntensity, colorA, colorB) {
    try {
      var fx = fxParade(layer).addProperty("ADBE Glo2");
      fx.name = name;
      setFxValue(fx, "ADBE Glo2-0002", "Glow Threshold", threshold);
      setFxValue(fx, "ADBE Glo2-0003", "Glow Radius", radius);
      setFxExpr(fx, "ADBE Glo2-0004", "Glow Intensity", glowIntensityExpr(baseIntensity));
      setFxValue(fx, "ADBE Glo2-0006", "Glow Operation", 1); // Add
      setFxValue(fx, "ADBE Glo2-0007", "Glow Colors", 2);    // A & B Colors
      var pa = findFxProp(fx, "ADBE Glo2-0012", "Color A");
      var pb = findFxProp(fx, "ADBE Glo2-0013", "Color B");
      if (pa) applyColorSafe(pa, colorA);
      if (pb) applyColorSafe(pb, colorB);
    } catch (err) { /* glow is decorative — skip if unavailable */ }
  }

  function addGlowStack(layer, k, colors, full) {
    addOneGlow(layer, "Glow 1 — Tight Core", 65, 16 * k, 3.0, colors.highlight, colors.fill);
    if (full) {
      addOneGlow(layer, "Glow 2 — Medium Spread", 50, 100 * k, 1.0, colors.highlight, colors.fill);
      addOneGlow(layer, "Glow 3 — Wide Fall-off", 80, 500 * k, 0.5, colors.highlight, colors.fill);
    }
  }

  /* ---- Gradient shading ---------------------------------------------------
   * Shape gradient STOP colors aren't scriptable, so gradients are drawn in
   * plain white→black (geometry/direction IS scriptable) and a Tritone
   * effect remaps luminance to this item's highlight/body/shadow tones —
   * which are expression-linked to the master color, keeping gradients
   * fully live. White art (caps, rims) maps to Highlights; black strokes
   * map to Shadows. */
  function addTritoneFx(layer, colors) {
    try {
      var fx = fxParade(layer).addProperty("ADBE Tritone");
      fx.name = "Tone Map — drives gradient colors";
      var hi = findFxProp(fx, "ADBE Tritone-0001", "Highlights");
      var mid = findFxProp(fx, "ADBE Tritone-0002", "Midtones");
      var sh = findFxProp(fx, "ADBE Tritone-0003", "Shadows");
      if (hi) applyColorSafe(hi, colors.highlight);
      if (mid) applyColorSafe(mid, colors.fill);
      if (sh) applyColorSafe(sh, colors.outline);
    } catch (err) {}
  }

  /* Fill effect so every label follows the controller's Label Color live. */
  function addLabelColorFx(layer) {
    try {
      var fx = fxParade(layer).addProperty("ADBE Fill");
      var col = null;
      try { col = fx.property("ADBE Fill-0002"); } catch (e1) { col = null; }
      if (!col) col = fx.property("Color");
      col.expression = labelColorExpr();
    } catch (err) { /* label stays static near-white — acceptable fallback */ }
  }

  function addGroupWithPath(layer, groupName, shape, closed) {
    var grp = layer.property("ADBE Root Vectors Group").addProperty("ADBE Vector Group");
    grp.name = groupName;
    var cont = grp.property("ADBE Vectors Group");
    var pathProp = cont.addProperty("ADBE Vector Shape - Group");
    var sh = new Shape();
    sh.vertices = shape;
    sh.closed = !!closed;
    pathProp.property("ADBE Vector Shape").setValue(sh);
    return cont;
  }

  function addStroke(cont, widthOrExpr, colorExprOrValue, capButt) {
    var st = cont.addProperty("ADBE Vector Graphic - Stroke");
    if (typeof widthOrExpr === "string") st.property("ADBE Vector Stroke Width").expression = widthOrExpr;
    else st.property("ADBE Vector Stroke Width").setValue(widthOrExpr);
    if (typeof colorExprOrValue === "string") st.property("ADBE Vector Stroke Color").expression = colorExprOrValue;
    else st.property("ADBE Vector Stroke Color").setValue(colorExprOrValue);
    if (capButt) {
      try { st.property("ADBE Vector Stroke Line Cap").setValue(1); } catch (e) {}
    }
    return st;
  }

  function itemTone(i, n) {
    return n > 1 ? (i / (n - 1) - 0.5) : 0;
  }

  function itemFillColorSpec(cfg, i, n) {
    // Returns {expr:...} for ramped tones or {value:[r,g,b,a]} for overrides.
    // fill = body tone, outline = darkened edge, highlight = brightened sheen.
    var it = cfg.items[i];
    if (it.useCustom) {
      var rgb = hexToRgb(it.color);
      return { fill: { value: [rgb[0], rgb[1], rgb[2], 1] },
               outline: { value: [rgb[0] * 0.55, rgb[1] * 0.55, rgb[2] * 0.55, 1] },
               highlight: { value: [Math.min(rgb[0] * 1.5 + 0.08, 1), Math.min(rgb[1] * 1.5 + 0.08, 1), Math.min(rgb[2] * 1.5 + 0.08, 1), 1] } };
    }
    var t = itemTone(i, n);
    return { fill: { expr: rampColorExpr(t, 1) },
             outline: { expr: rampColorExpr(t, 0.55) },
             highlight: { expr: rampColorExpr(t, 1.5) } };
  }

  function applyColor(prop, spec) {
    if (spec.expr) prop.expression = spec.expr;
    else prop.setValue(spec.value);
  }

  function sum(items) {
    var s = 0;
    for (var i = 0; i < items.length; i++) s += items[i].value;
    return s;
  }

  function maxVal(items) {
    var m = 0;
    for (var i = 0; i < items.length; i++) if (items[i].value > m) m = items[i].value;
    return m;
  }

  // =================================================== axes / grid / text

  function buildAxesAndTicks(comp, ctrl, geo, niceMax, step, fmt, total) {
    var left = geo.left, right = geo.right, base = geo.base, top = geo.top, k = geo.k;

    var axes = addShapeItem(comp, ctrl, "Axes & Gridlines", LC.axes);
    axes.position.setValue([0, 0]);

    // Gridlines (behind everything else in this layer's stacking).
    var ticks = Math.max(1, Math.round(niceMax / step));
    for (var j = 1; j <= ticks; j++) {
      var tv = step * j;
      var y = base - geo.ph * (tv / niceMax);
      var cont = addGroupWithPath(axes, "Gridline " + formatStatic(tv, fmt, total), [[left, y], [right, y]], false);
      var st = addStroke(cont, 2 * k, labelColorExpr(), false);
      st.property("ADBE Vector Stroke Opacity").setValue(22);
    }

    // Axis lines.
    var contY = addGroupWithPath(axes, "Y Axis", [[left, base], [left, top]], false);
    addStroke(contY, 3 * k, labelColorExpr(), false);
    var contX = addGroupWithPath(axes, "Baseline (X Axis)", [[left, base], [right, base]], false);
    addStroke(contX, 3 * k, labelColorExpr(), false);

    // Axes fade in just before the build starts.
    axes.opacity.expression =
      'var C=thisComp.layer("' + CTRL_NAME + '");\n' +
      'var dly=C.effect("ANIM | Start Delay")(1);\n' +
      'clamp((time-inPoint-dly+0.25)/0.35,0,1)*100';

    // Tick value labels (incl. zero at the baseline) — smallest and lightest
    // tier of the type scale, muted to 80% so data labels stay dominant.
    for (var j2 = 0; j2 <= ticks; j2++) {
      var tv2 = step * j2;
      var y2 = base - geo.ph * (tv2 / niceMax);
      var lab = addTextItem(comp, ctrl, "Y Tick — " + formatStatic(tv2, fmt, total),
        formatStatic(tv2, fmt, total), 22 * k, ParagraphJustification.RIGHT_JUSTIFY, "regular", LC.tick);
      lab.position.setValue([left - 16 * k, y2 + 8 * k]);
      lab.opacity.expression =
        'var C=thisComp.layer("' + CTRL_NAME + '");\n' +
        'var dly=C.effect("ANIM | Start Delay")(1);\n' +
        'clamp((time-inPoint-dly+0.25)/0.35,0,1)*80';
    }
  }

  function buildLegend(comp, ctrl, geo, cfg) {
    var k = geo.k;
    var y = geo.top - 52 * k;

    var swatch = addShapeItem(comp, ctrl, "Legend Swatch", LC.legend);
    swatch.position.setValue([geo.left + 13 * k, y]);
    var grp = swatch.property("ADBE Root Vectors Group").addProperty("ADBE Vector Group");
    grp.name = "Swatch";
    var cont = grp.property("ADBE Vectors Group");
    var rect = cont.addProperty("ADBE Vector Shape - Rect");
    rect.property("ADBE Vector Rect Size").setValue([26 * k, 26 * k]);
    rect.property("ADBE Vector Rect Roundness").setValue(6 * k);
    var fill = cont.addProperty("ADBE Vector Graphic - Fill");
    fill.property("ADBE Vector Fill Color").expression = rampColorExpr(0, 1);
    swatch.opacity.expression = 'clamp((time-inPoint)/0.4,0,1)*100';

    var lab = addTextItem(comp, ctrl, "Legend — \"" + cfg.seriesName + "\"",
      cfg.seriesName, 26 * k, ParagraphJustification.LEFT_JUSTIFY, "medium", LC.legend);
    lab.position.setValue([geo.left + 34 * k, y + 9 * k]);
    lab.opacity.expression = 'clamp((time-inPoint)/0.4,0,1)*100';
  }

  function buildTitle(comp, ctrl, cfg, x, y, k) {
    if (!cfg.title) return;
    var lab = addTextItem(comp, ctrl, "Chart Title — \"" + cfg.title + "\"",
      cfg.title, 54 * k, ParagraphJustification.CENTER_JUSTIFY, "bold", LC.title);
    lab.position.setValue([x, y]);
    lab.opacity.expression = 'clamp((time-inPoint)/0.4,0,1)*100';
  }

  // ============================================================ bar chart

  function buildBar(comp, ctrl, cfg, k) {
    var n = cfg.items.length;
    var pw = 1440 * k, ph = 700 * k;
    var geo = { pw: pw, ph: ph, left: -pw / 2, right: pw / 2, base: ph / 2, top: -ph / 2, k: k };

    var total = sum(cfg.items);
    var step = niceStep(maxVal(cfg.items), 5);
    var niceMax = Math.ceil(maxVal(cfg.items) / step) * step;
    if (niceMax <= 0) niceMax = 1;

    buildAxesAndTicks(comp, ctrl, geo, niceMax, step, cfg.format, total);

    var slot = pw / n;
    var barW = slot * 0.62;

    // Layers are created bottom-up in organized blocks — bars, then
    // category labels, then value labels — so the timeline reads as tidy
    // groups instead of interleaved per-bar layers. Reverse order within
    // each block keeps 01 at the top of its group.
    for (var i = n - 1; i >= 0; i--) {
      var it = cfg.items[i];
      var x = geo.left + slot * (i + 0.5);
      var h = ph * (it.value / niceMax);
      var colors = itemFillColorSpec(cfg, i, n);

      // --- the bar itself -------------------------------------------------
      var bar = addShapeItem(comp, ctrl, "Bar " + pad2(i + 1) + " — \"" + it.label + "\"", LC.bar);
      bar.position.setValue([x, geo.base]);

      // Bright cap along the growing top edge (added first = renders in
      // front). Its height is capped by the bar's own height so nothing
      // shows before the build starts.
      var capH = 12 * k;
      var hgrp = bar.property("ADBE Root Vectors Group").addProperty("ADBE Vector Group");
      hgrp.name = "Top Highlight";
      var hcont = hgrp.property("ADBE Vectors Group");
      var hrect = hcont.addProperty("ADBE Vector Shape - Rect");
      hrect.property("ADBE Vector Rect Size").expression =
        preamble(i) + 'var hh=Math.max(' + round3(h) + '*e,0);\n[' + round3(barW * 0.9) + ',Math.min(' + round3(capH) + ',hh)]';
      hrect.property("ADBE Vector Rect Position").expression =
        preamble(i) + 'var hh=Math.max(' + round3(h) + '*e,0);\n[0,-hh+Math.min(' + round3(capH) + ',hh)/2]';
      var hfill = hcont.addProperty("ADBE Vector Graphic - Fill");
      hfill.property("ADBE Vector Fill Color").setValue([1, 1, 1, 1]); // → Highlights tone via Tritone

      var grp = bar.property("ADBE Root Vectors Group").addProperty("ADBE Vector Group");
      grp.name = "Bar";
      var cont = grp.property("ADBE Vectors Group");
      var rect = cont.addProperty("ADBE Vector Shape - Rect");
      rect.property("ADBE Vector Rect Size").expression =
        preamble(i) + '[' + round3(barW) + ',Math.max(' + round3(h) + '*e,0)]';
      rect.property("ADBE Vector Rect Position").expression =
        preamble(i) + '[0,-Math.max(' + round3(h) + '*e,0)/2]';
      // True vertical gradient: a white→black gradient fill whose start
      // point rides the growing top edge; Tritone maps it to this item's
      // tones, live-linked to the master color.
      var gfill = null;
      try {
        gfill = cont.addProperty("ADBE Vector Graphic - G-Fill");
        try { gfill.property("ADBE Vector Grad Type").setValue(1); } catch (eT) {} // linear
        gfill.property("ADBE Vector Grad Start Pt").expression =
          preamble(i) + '[0,-Math.max(' + round3(h) + '*e,1)]';
        gfill.property("ADBE Vector Grad End Pt").setValue([0, 0]);
      } catch (eG) { gfill = null; }
      if (!gfill) { // very old AE — flat fill fallback
        var fill = cont.addProperty("ADBE Vector Graphic - Fill");
        applyColor(fill.property("ADBE Vector Fill Color"), colors.fill);
      }
      var st = cont.addProperty("ADBE Vector Graphic - Stroke");
      st.property("ADBE Vector Stroke Width").expression = outlineWidthExpr();
      st.property("ADBE Vector Stroke Color").setValue([0, 0, 0, 1]); // → Shadows tone via Tritone

      addTritoneFx(bar, colors);
      addGlowStack(bar, k, colors, true);
    }

    // --- category labels under the baseline (own block in the timeline) ----
    for (var i2 = n - 1; i2 >= 0; i2--) {
      var itC = cfg.items[i2];
      var clab = addTextItem(comp, ctrl, "Category " + pad2(i2 + 1) + " — \"" + itC.label + "\"",
        itC.label, 27 * k, ParagraphJustification.CENTER_JUSTIFY, "medium", LC.category);
      clab.position.setValue([geo.left + slot * (i2 + 0.5), geo.base + 44 * k]);
      clab.opacity.expression = preamble(i2) + 'clamp(p*3,0,1)*100';
    }

    // --- count-up value labels: big, bold, tight to the bar tops -----------
    for (var i3 = n - 1; i3 >= 0; i3--) {
      var itV = cfg.items[i3];
      var xV = geo.left + slot * (i3 + 0.5);
      var hV = ph * (itV.value / niceMax);
      var vlab = addTextItem(comp, ctrl, "Value " + pad2(i3 + 1) + " — \"" + itV.label + "\"",
        formatStatic(itV.value, cfg.format, total), 72 * k, ParagraphJustification.CENTER_JUSTIFY, "bold", LC.value);
      vlab.position.expression =
        preamble(i3) + '[' + round3(xV) + ',' + round3(geo.base) + '-Math.max(' + round3(hV) + '*e,0)-' + round3(20 * k) + ']';
      vlab.property("ADBE Text Properties").property("ADBE Text Document").expression =
        preamble(i3) + countUpBody(itV.value, total, cfg.format) + 'out';
      vlab.opacity.expression = preamble(i3) + 'clamp(p*4,0,1)*100';
    }

    buildLegend(comp, ctrl, geo, cfg);
    buildTitle(comp, ctrl, cfg, 0, geo.top - 110 * k, k);
    return geo;
  }

  // =========================================================== line chart

  function buildLine(comp, ctrl, cfg, k) {
    var n = cfg.items.length;
    var pw = 1440 * k, ph = 700 * k;
    var geo = { pw: pw, ph: ph, left: -pw / 2, right: pw / 2, base: ph / 2, top: -ph / 2, k: k };

    var total = sum(cfg.items);
    var step = niceStep(maxVal(cfg.items), 5);
    var niceMax = Math.ceil(maxVal(cfg.items) / step) * step;
    if (niceMax <= 0) niceMax = 1;

    buildAxesAndTicks(comp, ctrl, geo, niceMax, step, cfg.format, total);

    // Point positions (padded inside the plot box).
    var pad = 50 * k;
    var usable = pw - pad * 2;
    var pts = [];
    var i;
    for (i = 0; i < n; i++) {
      var x = geo.left + pad + usable * (n > 1 ? i / (n - 1) : 0.5);
      var y = geo.base - ph * (cfg.items[i].value / niceMax);
      pts.push([x, y]);
    }

    // Cumulative path-length fraction of each point — labels/dots pop as the
    // trim-paths draw-on passes them.
    var lens = [0];
    var totalLen = 0;
    for (i = 1; i < n; i++) {
      var dx = pts[i][0] - pts[i - 1][0];
      var dy = pts[i][1] - pts[i - 1][1];
      totalLen += Math.sqrt(dx * dx + dy * dy);
      lens.push(totalLen);
    }
    var fracs = [];
    for (i = 0; i < n; i++) {
      var f = totalLen > 0 ? lens[i] / totalLen : 0;
      fracs.push(Math.min(f * 0.97, 0.97)); // nudge earlier so the last dot fires
    }

    // --- soft area fill under the line (fades in as the line draws) --------
    var apts = [];
    for (i = 0; i < n; i++) apts.push(pts[i]);
    apts.push([pts[n - 1][0], geo.base]);
    apts.push([pts[0][0], geo.base]);
    var area = addShapeItem(comp, ctrl, "Area Fill — \"" + cfg.seriesName + "\"", LC.area);
    area.position.setValue([0, 0]);
    var acont = addGroupWithPath(area, "Area", apts, true);
    var afill = acont.addProperty("ADBE Vector Graphic - Fill");
    afill.property("ADBE Vector Fill Color").expression = rampColorExpr(0, 1);
    area.opacity.expression = preamble(0) + 'Math.min(e,1)*26';
    // Soft alpha fade toward the baseline (gradient-fill opacity stops are
    // not scriptable — a heavily feathered Linear Wipe does the same job).
    try {
      var wipe = fxParade(area).addProperty("ADBE Linear Wipe");
      setFxValue(wipe, "ADBE Linear Wipe-0001", "Transition Completion", 35);
      setFxValue(wipe, "ADBE Linear Wipe-0002", "Wipe Angle", 0);
      setFxValue(wipe, "ADBE Linear Wipe-0003", "Feather", 700 * k);
    } catch (eW) {}

    // --- the line -----------------------------------------------------------
    var line = addShapeItem(comp, ctrl, "Chart Line — \"" + cfg.seriesName + "\"", LC.line);
    line.position.setValue([0, 0]);
    var cont = addGroupWithPath(line, "Line", pts, false);
    var trim = cont.addProperty("ADBE Vector Filter - Trim");
    trim.property("ADBE Vector Trim Start").setValue(0);
    trim.property("ADBE Vector Trim End").expression = preamble(0) + 'Math.min(e,1)*100';
    var st = cont.addProperty("ADBE Vector Graphic - Stroke");
    st.property("ADBE Vector Stroke Width").expression =
      'thisComp.layer("' + CTRL_NAME + '").effect("STYLE | Line Weight")(1)';
    st.property("ADBE Vector Stroke Color").expression = rampColorExpr(0, 1);
    try { st.property("ADBE Vector Stroke Line Cap").setValue(2); } catch (eCap) {} // round
    var lineColors = { fill: { expr: rampColorExpr(0, 1) }, highlight: { expr: rampColorExpr(0, 1.5) } };
    addGlowStack(line, k, lineColors, true);

    // Pop timing: each point pops in over a short window after the draw-on
    // passes it. The window shrinks near the end of the path so the LAST
    // point still completes its pop at exactly progress = 1 (a fixed-width
    // window left it stranded at ~22% opacity).
    var wins = [];
    for (i = 0; i < n; i++) wins.push(Math.max(0.001, Math.min(0.08, 1 - fracs[i])));
    function popPre(idx) {
      return preamble(0) +
        'var pp=clamp((Math.min(e,1)-' + round6(fracs[idx]) + ')/' + round6(wins[idx]) + ',0,1);pp=pp*pp*(3-2*pp);\n';
    }

    // Layers are created bottom-up in organized blocks: dots, then category
    // labels, then value labels. Reverse order keeps 01 on top per block.
    for (i = n - 1; i >= 0; i--) {
      var it = cfg.items[i];
      var colors = itemFillColorSpec(cfg, i, n);

      var dot = addShapeItem(comp, ctrl, "Point " + pad2(i + 1) + " — \"" + it.label + "\"", LC.dot);
      dot.position.setValue(pts[i]);
      var dgrp = dot.property("ADBE Root Vectors Group").addProperty("ADBE Vector Group");
      dgrp.name = "Dot";
      var dcont = dgrp.property("ADBE Vectors Group");
      var ell = dcont.addProperty("ADBE Vector Shape - Ellipse");
      ell.property("ADBE Vector Ellipse Size").setValue([18 * k, 18 * k]);
      // Glossy dot: bright core with a base-tone ring, like the reference.
      var dfill = dcont.addProperty("ADBE Vector Graphic - Fill");
      applyColor(dfill.property("ADBE Vector Fill Color"), colors.highlight);
      var dst = dcont.addProperty("ADBE Vector Graphic - Stroke");
      dst.property("ADBE Vector Stroke Width").expression = outlineWidthExpr();
      applyColor(dst.property("ADBE Vector Stroke Color"), colors.fill);
      // pop with a little overshoot as the line arrives
      dot.scale.expression = popPre(i) +
        'var s=1.70158,u=pp-1;var eb=1+(s+1)*u*u*u+s*u*u;\n[100*eb,100*eb]';
      addGlowStack(dot, k, colors, false); // core tier only — 3 glows × 60 dots would crawl
    }

    for (i = n - 1; i >= 0; i--) {
      var itC = cfg.items[i];
      var clab = addTextItem(comp, ctrl, "Category " + pad2(i + 1) + " — \"" + itC.label + "\"",
        itC.label, 27 * k, ParagraphJustification.CENTER_JUSTIFY, "medium", LC.category);
      clab.position.setValue([pts[i][0], geo.base + 44 * k]);
      clab.opacity.expression = popPre(i) + 'pp*100';
    }

    for (i = n - 1; i >= 0; i--) {
      var itV = cfg.items[i];
      var vlab = addTextItem(comp, ctrl, "Value " + pad2(i + 1) + " — \"" + itV.label + "\"",
        formatStatic(itV.value, cfg.format, total), 34 * k, ParagraphJustification.CENTER_JUSTIFY, "bold", LC.value);
      vlab.position.setValue([pts[i][0], pts[i][1] - 36 * k]);
      vlab.property("ADBE Text Properties").property("ADBE Text Document").expression =
        popPre(i) + countUpBody(itV.value, total, cfg.format, "pp") + 'out';
      vlab.opacity.expression = popPre(i) + 'pp*100';
    }

    buildLegend(comp, ctrl, geo, cfg);
    buildTitle(comp, ctrl, cfg, 0, geo.top - 110 * k, k);
    return geo;
  }

  // ============================================================ pie chart

  /* Slices use the classic trim-path trick: a circle path of radius R/2 with
   * a stroke R wide fills the full disc; Trim Start/End carve the wedge.
   *
   * The reveal is ONE continuous radial sweep from 12 o'clock: a single
   * eased progress G (0..1 of the full circle, no per-slice stagger) drives
   * every slice, and each slice shows the clamped window [cum, cum+frac] of
   * G — so wedges grow adjacent to each other as the sweep passes through
   * them. Every slice layer's opacity is gated on the sweep reaching its
   * start angle, so nothing is visible before the animation begins. */
  function buildPie(comp, ctrl, cfg, k) {
    var R = 330 * k;
    var n = cfg.items.length;

    var order = [];
    var i;
    for (i = 0; i < n; i++) order.push(i);
    if (cfg.pie.sortDesc) {
      order.sort(function (a, b) { return cfg.items[b].value - cfg.items[a].value; });
    }

    var total = sum(cfg.items);
    var fracs = [];
    for (i = 0; i < n; i++) fracs.push(cfg.items[order[i]].value / total);

    var SWEEP = preamble(0) + 'var G=Math.min(e,1);\n';

    // Pre-compute label slots and resolve vertical collisions per side.
    var cum = 0;
    var slices = [];
    for (i = 0; i < n; i++) {
      var frac = fracs[i];
      var midT = cum + frac / 2;                 // 0..1 around the clock
      var theta = midT * 2 * Math.PI;            // from 12 o'clock, clockwise
      var dir = [Math.sin(theta), -Math.cos(theta)];
      slices.push({
        idx: order[i], frac: frac, cum: cum, dir: dir,
        side: dir[0] >= 0 ? 1 : -1,
        labelY: dir[1] * (R + 60 * k)
      });
      cum += frac;
    }
    // Labels are two lines tall (name + bold percent) — space accordingly.
    resolveLabelCollisions(slices, 1, 86 * k, R + 140 * k);
    resolveLabelCollisions(slices, -1, 86 * k, R + 140 * k);

    var rimW = 12 * k;

    // Layers are created bottom-up in organized blocks: slices, outline
    // ring, leader lines, then labels — tidy groups in the timeline, 01 at
    // the top of each block.
    for (i = n - 1; i >= 0; i--) {
      var s = slices[i];
      var it = cfg.items[s.idx];
      var colors = itemFillColorSpec(cfg, i, n);
      var pct = s.frac * 100;
      var niceName = "\"" + it.label + "\" (" + pct.toFixed(1) + "%)";
      var c0 = round6(s.cum);
      var c1 = round6(s.cum + s.frac);
      var trimEndExpr = SWEEP + 'clamp(G,' + c0 + ',' + c1 + ')*100';
      var gateExpr = SWEEP + '(G>' + c0 + ')?100:0';

      // --- slice -----------------------------------------------------------
      var slice = addShapeItem(comp, ctrl, "Pie Slice " + pad2(i + 1) + " — " + niceName, LC.slice);
      slice.position.setValue([0, 0]);

      // Bright rim along the outer edge (added first = renders in front),
      // swept with the slice — the glossy edge from the reference look.
      var rgrp2 = slice.property("ADBE Root Vectors Group").addProperty("ADBE Vector Group");
      rgrp2.name = "Rim Highlight";
      var rcont2 = rgrp2.property("ADBE Vectors Group");
      var rell2 = rcont2.addProperty("ADBE Vector Shape - Ellipse");
      rell2.property("ADBE Vector Ellipse Size").setValue([2 * R - rimW, 2 * R - rimW]);
      var rtrim2 = rcont2.addProperty("ADBE Vector Filter - Trim");
      rtrim2.property("ADBE Vector Trim Start").setValue(c0 * 100);
      rtrim2.property("ADBE Vector Trim End").expression = trimEndExpr;
      var rst2 = rcont2.addProperty("ADBE Vector Graphic - Stroke");
      rst2.property("ADBE Vector Stroke Width").setValue(rimW);
      rst2.property("ADBE Vector Stroke Color").setValue([1, 1, 1, 1]); // → Highlights tone via Tritone
      try { rst2.property("ADBE Vector Stroke Line Cap").setValue(1); } catch (eCap1) {}

      var grp = slice.property("ADBE Root Vectors Group").addProperty("ADBE Vector Group");
      grp.name = "Slice";
      var cont = grp.property("ADBE Vectors Group");
      var ell = cont.addProperty("ADBE Vector Shape - Ellipse");
      ell.property("ADBE Vector Ellipse Size").setValue([R, R]); // path radius R/2
      var trim = cont.addProperty("ADBE Vector Filter - Trim");
      trim.property("ADBE Vector Trim Start").setValue(c0 * 100);
      trim.property("ADBE Vector Trim End").expression = trimEndExpr;
      // Radial white→black gradient stroke (bright center, dark edge);
      // Tritone maps it to this slice's tones, live via the master color.
      var st = null;
      try {
        st = cont.addProperty("ADBE Vector Graphic - G-Stroke");
        try { st.property("ADBE Vector Grad Type").setValue(2); } catch (eT2) {} // radial
        try { st.property("ADBE Vector Grad Start Pt").setValue([0, 0]); } catch (eP1) {}
        try { st.property("ADBE Vector Grad End Pt").setValue([R, 0]); } catch (eP2) {}
      } catch (eGS) { st = null; }
      if (!st) { // very old AE — flat stroke fallback
        st = cont.addProperty("ADBE Vector Graphic - Stroke");
        applyColor(st.property("ADBE Vector Stroke Color"), colors.fill);
      }
      st.property("ADBE Vector Stroke Width").setValue(R);
      try { st.property("ADBE Vector Stroke Line Cap").setValue(1); } catch (eCap) {} // butt = radial edges

      // Hidden until the sweep reaches this slice — nothing pre-renders.
      slice.opacity.expression = gateExpr;
      addTritoneFx(slice, colors);
      addGlowStack(slice, k, colors, true);
    }

    // Darker outline ring around the pie's edge, drawn by the same sweep —
    // sits just above the slices in the stack.
    var ring = addShapeItem(comp, ctrl, "Pie Outline Ring", LC.ring);
    ring.position.setValue([0, 0]);
    var rgrp = ring.property("ADBE Root Vectors Group").addProperty("ADBE Vector Group");
    rgrp.name = "Ring";
    var rcont = rgrp.property("ADBE Vectors Group");
    var rell = rcont.addProperty("ADBE Vector Shape - Ellipse");
    rell.property("ADBE Vector Ellipse Size").setValue([R * 2, R * 2]);
    var rtrim = rcont.addProperty("ADBE Vector Filter - Trim");
    rtrim.property("ADBE Vector Trim Start").setValue(0);
    rtrim.property("ADBE Vector Trim End").expression = SWEEP + 'G*100';
    var rst = rcont.addProperty("ADBE Vector Graphic - Stroke");
    rst.property("ADBE Vector Stroke Width").expression = outlineWidthExpr();
    rst.property("ADBE Vector Stroke Color").expression = rampColorExpr(0, 0.55);
    ring.opacity.expression = SWEEP + '(G>0)?100:0';

    // Labels appear as the sweep crosses each slice's midpoint.
    function labelLP(sl) {
      var mid = round6(sl.cum + sl.frac / 2);
      var win = round6(Math.max(sl.frac / 2, 0.04));
      return SWEEP + 'var lp=clamp((G-' + mid + ')/' + win + ',0,1);lp=lp*lp*(3-2*lp);\n';
    }

    // --- leader lines (own block) -------------------------------------------
    for (i = n - 1; i >= 0; i--) {
      s = slices[i];
      it = cfg.items[s.idx];
      niceName = "\"" + it.label + "\" (" + (s.frac * 100).toFixed(1) + "%)";
      var LP = labelLP(s);
      var p0 = [s.dir[0] * (R - 4 * k), s.dir[1] * (R - 4 * k)];
      var p1 = [s.dir[0] * (R + 40 * k), s.dir[1] * (R + 40 * k)];
      var p2 = [s.side * (R + 120 * k), s.labelY];
      var leader = addShapeItem(comp, ctrl, "Leader " + pad2(i + 1) + " — " + niceName, LC.leader);
      leader.position.setValue([0, 0]);
      var lcont = addGroupWithPath(leader, "Leader", [p0, p1, p2], false);
      var ltrim = lcont.addProperty("ADBE Vector Filter - Trim");
      ltrim.property("ADBE Vector Trim Start").setValue(0);
      ltrim.property("ADBE Vector Trim End").expression = LP + 'lp*100';
      addStroke(lcont, 2 * k, labelColorExpr(), false);
    }

    // --- external labels: name (medium) over a bold count-up percent --------
    for (i = n - 1; i >= 0; i--) {
      s = slices[i];
      it = cfg.items[s.idx];
      pct = s.frac * 100;
      niceName = "\"" + it.label + "\" (" + pct.toFixed(1) + "%)";
      var LP2 = labelLP(s);
      var just = s.side > 0 ? ParagraphJustification.LEFT_JUSTIFY : ParagraphJustification.RIGHT_JUSTIFY;
      var labX = s.side * (R + 120 * k) + s.side * 14 * k;

      var nameLab = addTextItem(comp, ctrl, "Label " + pad2(i + 1) + " — " + niceName,
        it.label, 27 * k, just, "medium", LC.category);
      nameLab.position.setValue([labX, s.labelY + 2 * k]);
      nameLab.opacity.expression = LP2 + 'lp*100';

      var pctStatic = (cfg.pie.includeValue ? formatStaticNumber(it.value, cfg.format) + " · " : "") +
        pct.toFixed(1) + "%";
      var pctLab = addTextItem(comp, ctrl, "Value " + pad2(i + 1) + " — " + niceName,
        pctStatic, 36 * k, just, "bold", LC.value);
      pctLab.position.setValue([labX, s.labelY + 42 * k]);
      var valPart = cfg.pie.includeValue
        ? '"' + escStr(formatStaticNumber(it.value, cfg.format)) + ' · "'
        : '""';
      pctLab.property("ADBE Text Properties").property("ADBE Text Document").expression =
        LP2 + valPart + '+(' + round3(pct) + '*lp).toFixed(1)+"%"';
      pctLab.opacity.expression = LP2 + 'lp*100';
    }

    buildTitle(comp, ctrl, cfg, 0, -R - 130 * k, k);
    return { k: k, r: R };
  }

  function formatStaticNumber(v, fmt) {
    var s = v.toFixed(fmt.decimals);
    if (fmt.thousands) s = thousandsStr(s);
    return (fmt.prefix || "") + s + (fmt.suffix || "");
  }

  /* Push overlapping labels apart (top to bottom) on one side of the pie. */
  function resolveLabelCollisions(slices, side, minGap, maxY) {
    var group = [];
    var i;
    for (i = 0; i < slices.length; i++) {
      if (slices[i].side === side) group.push(slices[i]);
    }
    group.sort(function (a, b) { return a.labelY - b.labelY; });
    for (i = 1; i < group.length; i++) {
      if (group[i].labelY < group[i - 1].labelY + minGap) {
        group[i].labelY = group[i - 1].labelY + minGap;
      }
    }
    // If the stack ran past the bottom, shift the whole side back up.
    if (group.length > 0) {
      var overflow = group[group.length - 1].labelY - maxY;
      if (overflow > 0) {
        for (i = 0; i < group.length; i++) group[i].labelY -= overflow;
      }
    }
  }

  // ================================================================ entry

  function generate(jsonStr) {
    var undoOpen = false;
    try {
      var cfg = parseJSON(jsonStr);
      if (!cfg || !cfg.items || cfg.items.length < 2) return "ERR|Need at least 2 data points.";

      app.beginUndoGroup("Graphinator: Generate Chart");
      undoOpen = true;

      var comp = getComp();
      var k = Math.min(comp.width / 1920, comp.height / 1080);
      CHART_FONTS = resolveFonts();

      removeItems(comp);
      var res = ensureController(comp, cfg);
      var ctrl = res.ctrl;

      if (cfg.type === "bar") buildBar(comp, ctrl, cfg, k);
      else if (cfg.type === "line") buildLine(comp, ctrl, cfg, k);
      else if (cfg.type === "pie") buildPie(comp, ctrl, cfg, k);
      else return "ERR|Unknown chart type: " + cfg.type;

      // Markers reflect the timing in force right now (live values if the
      // controller already existed). Refreshed on every Update.
      var anim = readAnimValues(ctrl, cfg);
      var startT = anim.delay;
      var endT;
      if (cfg.type === "bar") endT = anim.delay + anim.duration + anim.stagger * (cfg.items.length - 1);
      else if (cfg.type === "line") endT = anim.delay + anim.duration + 0.3; // label tail
      else endT = anim.delay + anim.duration + 0.6; // pie: single sweep + label tail
      setMarkers(ctrl, startT, endT);

      storeData(ctrl, jsonStr);
      ctrl.moveToBeginning();

      app.endUndoGroup();
      undoOpen = false;

      var msg = "Built " + cfg.type + " chart with " + cfg.items.length + " points in \"" + comp.name + "\". " +
        (res.isNew
          ? "Colors, timing & scale are now live on the controller layer."
          : "Controller kept — your live color/timing tweaks were preserved.");
      return "OK|" + msg;
    } catch (err) {
      if (undoOpen) { try { app.endUndoGroup(); } catch (e2) {} }
      return "ERR|" + (err && err.message ? err.message : String(err)) + (err && err.line ? " (jsx line " + err.line + ")" : "");
    }
  }

  function readData() {
    try {
      var comp = app.project.activeItem;
      if (!(comp && comp instanceof CompItem)) return "ERR|Open the comp that contains a Graphinator chart first.";
      var ctrl = findController(comp);
      if (!ctrl) return "ERR|No \"" + CTRL_NAME + "\" layer found in this comp.";
      var c = String(ctrl.comment);
      var idx = c.indexOf(DATA_TAG);
      if (idx < 0) return "ERR|The controller has no stored chart data.";
      return "DATA|" + c.substring(idx + DATA_TAG.length);
    } catch (err) {
      return "ERR|" + (err && err.message ? err.message : String(err));
    }
  }

  function setMasterColor(r, g, b) {
    try {
      var comp = app.project.activeItem;
      if (!(comp && comp instanceof CompItem)) return "ERR|No active comp.";
      var ctrl = findController(comp);
      if (!ctrl) return "ERR|No controller in this comp.";
      app.beginUndoGroup("Graphinator: Random Color");
      ctrl.property("ADBE Effect Parade").property("COLOR | Master Color").property(1)
        .setValue([r, g, b, 1]);
      app.endUndoGroup();
      return "OK|Master color updated.";
    } catch (err) {
      try { app.endUndoGroup(); } catch (e2) {}
      return "ERR|" + (err && err.message ? err.message : String(err));
    }
  }

  global.GRAPHINATOR = {
    generate: generate,
    readData: readData,
    setMasterColor: setMasterColor
  };

})($.global);
