/* Graphinator — ExtendScript chart builder.
 *
 * Called from the CEP panel via evalScript. Builds animated bar / line / pie
 * charts as native shape + text layers in the active comp.
 *
 * The hybrid contract:
 *   - The PANEL owns the data, chart type and number formatting. Pressing
 *     Update deletes every layer tagged GRAPHINATOR_ITEM and rebuilds it.
 *   - The ">> GRAPH CONTROLLER <<" null owns colors, animation timing and
 *     scale as LIVE effect controls; every generated layer derives from it
 *     via expressions. On Update the controller (and any tweaks made to it)
 *     is preserved — only its data blob and build markers are refreshed.
 *
 * Geometry is authored for a 1920x1080 comp (chart ≈ 75% of frame, wider
 * than tall for bar/line) and scaled proportionally for other comp sizes.
 */

(function (global) {

  // ------------------------------ FONT CONFIG ------------------------------
  // Default typeface for all chart text. If your font shows a different
  // family name in AE's Character panel, edit FONT_FAMILY here. Styles are
  // matched per weight from the candidate lists (first installed style
  // wins); Arial is the fallback when the family or AE's font API (24+)
  // is unavailable.
  var FONT_FAMILY = "Arthouse Owned";
  var FONT_STYLE_CANDIDATES = {
    regular: ["Regular", "Book", "Light", "Medium"],
    medium:  ["Medium", "Regular", "Book"],
    bold:    ["Bold", "Heavy", "Semibold", "SemiBold", "Demibold", "Black", "Medium"]
  };
  var FONT_FALLBACK_PS = { regular: "ArialMT", medium: "ArialMT", bold: "Arial-BoldMT" };
  // --------------------------------------------------------------------------

  var CTRL_NAME = ">> GRAPH CONTROLLER <<";

  // Timeline label colors — one per layer type so the stack reads at a
  // glance. (AE label indices: 1 Red, 2 Yellow, 3 Aqua, 4 Pink, 6 Peach,
  // 7 Sea Foam, 8 Blue, 9 Green, 10 Purple, 12 Brown, 15 Sandstone.)
  var LC = {
    controller: 10, // purple
    title: 1,       // red
    legend: 9,      // green
    value: 2,       // yellow — count-up value labels
    category: 6,    // peach — category names / pie names
    tick: 15,       // sandstone — muted axis ticks
    axes: 12,       // brown — axes & gridlines
    bar: 8,         // blue — bar shapes
    line: 8,        // blue — the chart line
    area: 7,        // sea foam — area fill
    dot: 4,         // pink — line points
    slice: 8,       // blue — pie slices
    ring: 12,       // brown — pie outline ring
    leader: 3       // aqua — pie leader lines
  };
  var ITEM_TAG = "GRAPHINATOR_ITEM";
  var CTRL_TAG = "GRAPHINATOR_CONTROLLER";
  var DATA_TAG = "@@GRAPHINATOR_DATA@@";

  var ITEM_COMMENT = ITEM_TAG + " — generated by the Graphinator panel. Manual edits to this layer are lost on Update.";

  var EASING_INDEX = { linear: 1, smooth: 2, overshoot: 3, bounce: 4 };

  // ================================================================ utils

  function parseJSON(text) {
    // Crockford-style validation, then eval (ExtendScript has no native JSON).
    var t = String(text);
    var cleaned = t
      .replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g, "@")
      .replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g, "]")
      .replace(/(?:^|:|,)(?:\s*\[)+/g, "");
    if (!/^[\],:{}\s]*$/.test(cleaned)) {
      throw new Error("Invalid config payload.");
    }
    return eval("(" + t + ")");
  }

  function escStr(s) {
    return String(s).replace(/\\/g, "\\\\").replace(/"/g, "\\\"");
  }

  function pad2(n) { return (n < 10 ? "0" : "") + n; }

  function hexToRgb(hex) {
    var h = String(hex).replace("#", "");
    if (h.length === 3) {
      h = h.charAt(0) + h.charAt(0) + h.charAt(1) + h.charAt(1) + h.charAt(2) + h.charAt(2);
    }
    return [
      parseInt(h.substr(0, 2), 16) / 255,
      parseInt(h.substr(2, 2), 16) / 255,
      parseInt(h.substr(4, 2), 16) / 255
    ];
  }

  function round3(v) { return Math.round(v * 1000) / 1000; }

  // Pie angles need more precision — adjacent wedges share exact boundaries.
  function round6(v) { return Math.round(v * 1000000) / 1000000; }

  function thousandsStr(s) {
    var pt = String(s).split(".");
    var x = pt[0];
    var neg = x.charAt(0) === "-";
    if (neg) x = x.substr(1);
    var r = "";
    var c = 0;
    for (var i = x.length - 1; i >= 0; i--) {
      r = x.charAt(i) + r;
      c++;
      if (c % 3 === 0 && i > 0) r = "," + r;
    }
    return (neg ? "-" : "") + r + (pt.length > 1 ? "." + pt[1] : "");
  }

  // Static (non-animated) number formatting for axis ticks etc.
  function formatStatic(v, fmt, total) {
    if (fmt.mode === "percent") {
      return (total > 0 ? (v / total * 100) : 0).toFixed(1) + "%";
    }
    var s = v.toFixed(fmt.decimals);
    if (fmt.thousands) s = thousandsStr(s);
    return (fmt.prefix || "") + s + (fmt.suffix || "");
  }

  function niceStep(range, targetTicks) {
    if (range <= 0) return 1;
    var raw = range / targetTicks;
    var mag = Math.pow(10, Math.floor(Math.log(raw) / Math.LN10));
    var norm = raw / mag;
    var step;
    if (norm < 1.5) step = 1;
    else if (norm < 3) step = 2;
    else if (norm < 7) step = 5;
    else step = 10;
    return step * mag;
  }

  // ====================================================== expression text

  /* Shared timing preamble. Defines p (raw 0..1 progress for item `index`,
   * staggered) and e (eased progress; may exceed 1 for Overshoot). */
  function preamble(index) {
    return 'var C=thisComp.layer("' + CTRL_NAME + '");\n' +
      'var dur=Math.max(C.effect("ANIM | Build Duration")(1),0.01);\n' +
      'var stag=C.effect("ANIM | Stagger")(1);\n' +
      'var dly=C.effect("ANIM | Start Delay")(1);\n' +
      'var sty=Math.round(C.effect("ANIM | Easing Style")(1));\n' +
      'function easeP(q){\n' +
      ' if(sty<=1)return q;\n' +
      ' if(sty==2)return q*q*(3-2*q);\n' +
      ' if(sty==3){var s=1.70158,u=q-1;return 1+(s+1)*u*u*u+s*u*u;}\n' +
      ' var n1=7.5625,d1=2.75,u=q;\n' +
      ' if(u<1/d1)return n1*u*u;\n' +
      ' if(u<2/d1){u-=1.5/d1;return n1*u*u+0.75;}\n' +
      ' if(u<2.5/d1){u-=2.25/d1;return n1*u*u+0.9375;}\n' +
      ' u-=2.625/d1;return n1*u*u+0.984375;\n' +
      '}\n' +
      'var p=clamp((time-inPoint-dly-' + index + '*stag)/dur,0,1);\n' +
      // Animate-out: a shared factor that reverses the build so the chart
      // finishes leaving exactly at the layer's out point.
      'var oEn=C.effect("ANIM | Out Enabled")(1);\n' +
      'var oDur=Math.max(C.effect("ANIM | Out Duration")(1),0.01);\n' +
      'var o=(oEn>0)?easeP(clamp((outPoint-time)/oDur,0,1)):1;\n' +
      'var e=easeP(p)*o;\n';
  }

  /* Fade for static furniture (axes, ticks, legend, title): in at the start,
   * out with the animate-out window. mult lets ticks sit muted at 80. */
  function staticFadeExpr(useDelay, mult) {
    return 'var C=thisComp.layer("' + CTRL_NAME + '");\n' +
      (useDelay ? 'var dly=C.effect("ANIM | Start Delay")(1);\n' : '') +
      'var oEn=C.effect("ANIM | Out Enabled")(1);\n' +
      'var oDur=Math.max(C.effect("ANIM | Out Duration")(1),0.01);\n' +
      'var o=(oEn>0)?clamp((outPoint-time)/oDur,0,1):1;\n' +
      (useDelay
        ? 'clamp((time-inPoint-dly+0.25)/0.35,0,1)*o*' + mult
        : 'clamp((time-inPoint)/0.4,0,1)*o*' + mult);
  }

  /* Live color ramp: derive this item's tone from the master color.
   * t is the baked tone offset (-0.5..0.5); mult darkens (outlines). */
  function rampColorExpr(t, mult) {
    return 'var C=thisComp.layer("' + CTRL_NAME + '");\n' +
      'var mc=C.effect("COLOR | Master Color")(1);\n' +
      'var sp=C.effect("COLOR | Tone Spread")(1)/100;\n' +
      'var h=rgbToHsl(mc);\n' +
      'var t=' + round3(t) + ';\n' +
      'var l=clamp(h[2]+t*sp*0.7,0.08,0.94)*' + mult + ';\n' +
      'var s=clamp(h[1]-t*sp*0.25,0.05,1);\n' +
      'hslToRgb([h[0],s,clamp(l,0,1),1])';
  }

  function labelColorExpr() {
    return 'thisComp.layer("' + CTRL_NAME + '").effect("STYLE | Label Color")(1)';
  }

  function outlineWidthExpr() {
    return 'thisComp.layer("' + CTRL_NAME + '").effect("STYLE | Outline Width")(1)';
  }

  var THS_FN =
    'function ths(str){var pt=(""+str).split(".");var x=pt[0];var ng=x.charAt(0)=="-";' +
    'if(ng)x=x.substr(1);var r="";var c=0;for(var i=x.length-1;i>=0;i--){r=x.charAt(i)+r;c++;' +
    'if(c%3==0&&i>0)r=","+r;}return (ng?"-":"")+r+(pt.length>1?"."+pt[1]:"");}\n';

  /* Count-up label body: uses `e` from the preamble, emits `out`. */
  function countUpBody(value, total, fmt, progressVar) {
    var pv = progressVar || "e";
    if (fmt.mode === "percent") {
      var share = total > 0 ? (value / total * 100) : 0;
      return 'var out=(' + round3(share) + '*' + pv + ').toFixed(1)+"%";\n';
    }
    var core = 'v.toFixed(' + fmt.decimals + ')';
    if (fmt.thousands) core = 'ths(' + core + ')';
    return THS_FN +
      'var v=' + round3(value) + '*' + pv + ';\n' +
      'var out="' + escStr(fmt.prefix || "") + '"+' + core + '+"' + escStr(fmt.suffix || "") + '";\n';
  }

  // ======================================================== layer helpers

  function getComp() {
    var comp = app.project.activeItem;
    if (!(comp && comp instanceof CompItem)) {
      comp = app.project.items.addComp("Graphinator Chart", 1920, 1080, 1.0, 10, 29.97);
      comp.openInViewer();
    }
    return comp;
  }

  function findController(comp) {
    for (var i = 1; i <= comp.numLayers; i++) {
      var lay = comp.layer(i);
      if (lay.name === CTRL_NAME && String(lay.comment).indexOf(CTRL_TAG) === 0) return lay;
      if (lay.name === CTRL_NAME) return lay; // renamed comment, still ours
    }
    return null;
  }

  function removeItems(comp) {
    for (var i = comp.numLayers; i >= 1; i--) {
      var lay = comp.layer(i);
      if (String(lay.comment).indexOf(ITEM_TAG) === 0) {
        lay.locked = false;
        lay.remove();
      }
    }
  }

  function fxParade(layer) {
    return layer.property("ADBE Effect Parade");
  }

  /* Add an effect control if it doesn't exist yet. Returns the effect and
   * whether it was just created (so panel defaults only seed new controls). */
  function ensureFx(layer, matchName, dispName, defVal) {
    var parade = fxParade(layer);
    var existing = null;
    try { existing = parade.property(dispName); } catch (e) { existing = null; }
    if (existing) return { fx: existing, created: false };
    var fx = parade.addProperty(matchName);
    fx.name = dispName;
    if (defVal !== null && defVal !== undefined) fx.property(1).setValue(defVal);
    return { fx: fx, created: true };
  }

  function ensureEasingFx(layer, defIndex) {
    var parade = fxParade(layer);
    var existing = null;
    try { existing = parade.property("ANIM | Easing Style"); } catch (e) { existing = null; }
    if (existing) return;
    try {
      var dd = parade.addProperty("ADBE Dropdown Control");
      // setPropertyParameters invalidates references; use what it returns.
      var menu = dd.property(1).setPropertyParameters(["Linear", "Smooth", "Overshoot", "Bounce"]);
      var eff = menu.propertyGroup(1);
      eff.name = "ANIM | Easing Style";
      eff.property(1).setValue(defIndex);
    } catch (err) {
      // Older AE without scriptable dropdowns — fall back to a slider.
      var sl = parade.addProperty("ADBE Slider Control");
      sl.name = "ANIM | Easing Style";
      sl.property(1).setValue(defIndex);
    }
  }

  function ensureController(comp, cfg) {
    var ctrl = findController(comp);
    var isNew = false;
    if (!ctrl) {
      ctrl = comp.layers.addNull(comp.duration);
      ctrl.name = CTRL_NAME;
      ctrl.anchorPoint.setValue([0, 0]);
      ctrl.position.setValue([comp.width / 2, comp.height / 2]);
      ctrl.label = 10; // purple — stands out in the timeline
      isNew = true;
    }

    var master = hexToRgb(cfg.color.master);
    var defs = [
      ["ADBE Color Control", "COLOR | Master Color", [master[0], master[1], master[2], 1]],
      ["ADBE Slider Control", "COLOR | Tone Spread", cfg.color.spread],
      ["ADBE Slider Control", "ANIM | Start Delay", cfg.anim.delay],
      ["ADBE Slider Control", "ANIM | Build Duration", cfg.anim.duration],
      ["ADBE Slider Control", "ANIM | Stagger", cfg.anim.stagger],
      ["ADBE Checkbox Control", "ANIM | Out Enabled", cfg.anim.outEnabled ? 1 : 0],
      ["ADBE Slider Control", "ANIM | Out Duration", cfg.anim.outDuration || 1],
      ["ADBE Slider Control", "STYLE | Donut Hole %", (cfg.pie && cfg.pie.donutHole) || 0],
      ["ADBE Slider Control", "STYLE | Outline Width", 4],
      ["ADBE Slider Control", "STYLE | Line Weight", 8],
      ["ADBE Checkbox Control", "STYLE | Glow Enabled", 1],
      ["ADBE Slider Control", "STYLE | Glow Intensity", 0.35],
      ["ADBE Color Control", "STYLE | Label Color", [0.95, 0.95, 0.95, 1]],
      ["ADBE Slider Control", "SCALE | Overall Scale", 100]
    ];
    for (var i = 0; i < defs.length; i++) {
      ensureFx(ctrl, defs[i][0], defs[i][1], defs[i][2]);
    }
    ensureEasingFx(ctrl, EASING_INDEX[cfg.anim.easing] || 2);

    // Whole chart scales about the comp center from one slider.
    ctrl.scale.expression =
      'var s=effect("SCALE | Overall Scale")(1);\n[s,s]';

    return { ctrl: ctrl, isNew: isNew };
  }

  function readAnimValues(ctrl, cfg) {
    // Live values win over panel values so Update respects controller tweaks.
    var a = { delay: cfg.anim.delay, duration: cfg.anim.duration, stagger: cfg.anim.stagger };
    try { a.delay = ctrl.property("ADBE Effect Parade").property("ANIM | Start Delay").property(1).value; } catch (e1) {}
    try { a.duration = ctrl.property("ADBE Effect Parade").property("ANIM | Build Duration").property(1).value; } catch (e2) {}
    try { a.stagger = ctrl.property("ADBE Effect Parade").property("ANIM | Stagger").property(1).value; } catch (e3) {}
    return a;
  }

  function setMarkers(ctrl, startT, endT) {
    var mp = ctrl.property("ADBE Marker");
    while (mp.numKeys > 0) mp.removeKey(1);
    mp.setValueAtTime(startT, new MarkerValue("BUILD START — timing is live in this layer's ANIM effects. Markers refresh on Update."));
    mp.setValueAtTime(endT, new MarkerValue("BUILD COMPLETE"));
  }

  function storeData(ctrl, jsonStr) {
    ctrl.comment =
      CTRL_TAG + "\n" +
      "— Colors, timing, outline & scale: LIVE here (select me > Effect Controls).\n" +
      "— Data, chart type & formatting: Window > Extensions > Graphinator, then Update.\n" +
      "— Manual edits to generated layers are lost on Update.\n" +
      DATA_TAG + jsonStr;
  }

  function tagItem(layer, ctrl) {
    layer.comment = ITEM_COMMENT;
    layer.setParentWithJump(ctrl);
    // Deselect immediately — selected layers make AE reveal their freshly
    // scripted properties, leaving the timeline twirled open after a build.
    try { layer.selected = false; } catch (eSel) {}
  }

  function addShapeItem(comp, ctrl, name, labelColor) {
    var lay = comp.layers.addShape();
    lay.name = name;
    if (labelColor) { try { lay.label = labelColor; } catch (eL) {} }
    tagItem(lay, ctrl);
    return lay;
  }

  /* Resolve the configured family's PostScript names per weight via the
   * font API (AE 24+). boldIsFaux flags a family with no real bold style,
   * so bold text can fall back to synthetic bold. */
  var CHART_FONTS = null;

  function resolveFonts() {
    var out = { boldIsFaux: false };
    var weights = ["regular", "medium", "bold"];
    for (var i = 0; i < weights.length; i++) {
      var w = weights[i];
      var ps = null;
      var chosenStyle = null;
      try {
        var cands = FONT_STYLE_CANDIDATES[w];
        for (var j = 0; j < cands.length && !ps; j++) {
          var arr = app.fonts.getFontsByFamilyNameAndStyleName(FONT_FAMILY, cands[j]);
          if (arr && arr.length > 0) { ps = arr[0].postScriptName; chosenStyle = cands[j]; }
        }
      } catch (e) { ps = null; }
      if (w === "bold" && ps && chosenStyle === "Medium") out.boldIsFaux = true;
      out[w] = ps || FONT_FALLBACK_PS[w];
    }
    return out;
  }

  function addTextItem(comp, ctrl, name, str, fontSize, justification, weight, labelColor) {
    var lay = comp.layers.addText(str);
    lay.name = name;
    if (labelColor) { try { lay.label = labelColor; } catch (eL) {} }
    var tp = lay.property("ADBE Text Properties").property("ADBE Text Document");
    var td = tp.value;
    td.fontSize = fontSize;
    var w = weight || "medium";
    try { td.font = CHART_FONTS[w]; } catch (eFont) {}
    if (w === "bold" && CHART_FONTS.boldIsFaux) {
      try { td.fauxBold = true; } catch (eFaux) {}
    }
    td.applyFill = true;
    td.fillColor = [0.95, 0.95, 0.95];
    td.applyStroke = false;
    td.justification = justification;
    tp.setValue(td);
    tagItem(lay, ctrl);
    addLabelColorFx(lay);
    return lay;
  }

  function findFxProp(fx, matchName, dispName) {
    var p = null;
    try { p = fx.property(matchName); } catch (e1) { p = null; }
    if (!p) { try { p = fx.property(dispName); } catch (e2) { p = null; } }
    return p;
  }

  function setFxValue(fx, m, d, v) { var p = findFxProp(fx, m, d); if (p) { try { p.setValue(v); } catch (e) {} } }
  function setFxExpr(fx, m, d, ex) { var p = findFxProp(fx, m, d); if (p) { try { p.expression = ex; } catch (e) {} } }

  function applyColorSafe(prop, spec) {
    try { applyColor(prop, spec); } catch (e) {}
  }

  /* ---- Pro glow stack ----------------------------------------------------
   * AE's single Glow is weak, so stack three: tight core, medium spread,
   * wide fall-off — all in Add mode with A & B colors derived from the
   * item's tone. Every tier is gated by STYLE | Glow Enabled and scaled by
   * STYLE | Glow Intensity on the controller, so the whole stack switches
   * off with one checkbox. */
  function glowIntensityExpr(base) {
    return 'var C=thisComp.layer("' + CTRL_NAME + '");\n' +
      'var on=C.effect("STYLE | Glow Enabled")(1);\n' +
      'var m=Math.max(C.effect("STYLE | Glow Intensity")(1),0);\n' +
      'on>0?' + base + '*m:0';
  }

  function addOneGlow(layer, name, threshold, radius, baseIntensity, colorA, colorB) {
    try {
      var fx = fxParade(layer).addProperty("ADBE Glo2");
      fx.name = name;
      setFxValue(fx, "ADBE Glo2-0002", "Glow Threshold", threshold);
      setFxValue(fx, "ADBE Glo2-0003", "Glow Radius", radius);
      setFxExpr(fx, "ADBE Glo2-0004", "Glow Intensity", glowIntensityExpr(baseIntensity));
      setFxValue(fx, "ADBE Glo2-0006", "Glow Operation", 1); // Add
      setFxValue(fx, "ADBE Glo2-0007", "Glow Colors", 2);    // A & B Colors
      var pa = findFxProp(fx, "ADBE Glo2-0012", "Color A");
      var pb = findFxProp(fx, "ADBE Glo2-0013", "Color B");
      if (pa) applyColorSafe(pa, colorA);
      if (pb) applyColorSafe(pb, colorB);
    } catch (err) { /* glow is decorative — skip if unavailable */ }
  }

  function addGlowStack(layer, k, colors, full) {
    addOneGlow(layer, "Glow 1 — Tight Core", 65, 16 * k, 3.0, colors.highlight, colors.fill);
    if (full) {
      addOneGlow(layer, "Glow 2 — Medium Spread", 50, 100 * k, 1.0, colors.highlight, colors.fill);
      addOneGlow(layer, "Glow 3 — Wide Fall-off", 80, 500 * k, 0.5, colors.highlight, colors.fill);
    }
  }

  /* ---- Gradient shading ---------------------------------------------------
   * Shape gradient STOP colors aren't scriptable, so gradients are drawn in
   * plain white→black (geometry/direction IS scriptable) and a Tritone
   * effect remaps luminance to this item's highlight/body/shadow tones —
   * which are expression-linked to the master color, keeping gradients
   * fully live. White art (caps, rims) maps to Highlights; black strokes
   * map to Shadows. */
  function addTritoneFx(layer, colors) {
    try {
      var fx = fxParade(layer).addProperty("ADBE Tritone");
      fx.name = "Tone Map — drives gradient colors";
      var hi = findFxProp(fx, "ADBE Tritone-0001", "Highlights");
      var mid = findFxProp(fx, "ADBE Tritone-0002", "Midtones");
      var sh = findFxProp(fx, "ADBE Tritone-0003", "Shadows");
      if (hi) applyColorSafe(hi, colors.highlight);
      if (mid) applyColorSafe(mid, colors.fill);
      if (sh) applyColorSafe(sh, colors.outline);
    } catch (err) {}
  }

  /* Fill effect so every label follows the controller's Label Color live. */
  function addLabelColorFx(layer) {
    try {
      var fx = fxParade(layer).addProperty("ADBE Fill");
      var col = null;
      try { col = fx.property("ADBE Fill-0002"); } catch (e1) { col = null; }
      if (!col) col = fx.property("Color");
      col.expression = labelColorExpr();
    } catch (err) { /* label stays static near-white — acceptable fallback */ }
  }

  function addGroupWithPath(layer, groupName, shape, closed) {
    var grp = layer.property("ADBE Root Vectors Group").addProperty("ADBE Vector Group");
    grp.name = groupName;
    var cont = grp.property("ADBE Vectors Group");
    var pathProp = cont.addProperty("ADBE Vector Shape - Group");
    var sh = new Shape();
    sh.vertices = shape;
    sh.closed = !!closed;
    pathProp.property("ADBE Vector Shape").setValue(sh);
    return cont;
  }

  function addStroke(cont, widthOrExpr, colorExprOrValue, capButt) {
    var st = cont.addProperty("ADBE Vector Graphic - Stroke");
    if (typeof widthOrExpr === "string") st.property("ADBE Vector Stroke Width").expression = widthOrExpr;
    else st.property("ADBE Vector Stroke Width").setValue(widthOrExpr);
    if (typeof colorExprOrValue === "string") st.property("ADBE Vector Stroke Color").expression = colorExprOrValue;
    else st.property("ADBE Vector Stroke Color").setValue(colorExprOrValue);
    if (capButt) {
      try { st.property("ADBE Vector Stroke Line Cap").setValue(1); } catch (e) {}
    }
    return st;
  }

  function itemTone(i, n) {
    return n > 1 ? (i / (n - 1) - 0.5) : 0;
  }

  function itemFillColorSpec(cfg, i, n) {
    // Returns {expr:...} for ramped tones or {value:[r,g,b,a]} for overrides.
    // fill = body tone, outline = darkened edge, highlight = brightened sheen.
    var it = cfg.items[i];
    if (it.useCustom) {
      var rgb = hexToRgb(it.color);
      return { fill: { value: [rgb[0], rgb[1], rgb[2], 1] },
               outline: { value: [rgb[0] * 0.55, rgb[1] * 0.55, rgb[2] * 0.55, 1] },
               highlight: { value: [Math.min(rgb[0] * 1.5 + 0.08, 1), Math.min(rgb[1] * 1.5 + 0.08, 1), Math.min(rgb[2] * 1.5 + 0.08, 1), 1] } };
    }
    var t = itemTone(i, n);
    return { fill: { expr: rampColorExpr(t, 1) },
             outline: { expr: rampColorExpr(t, 0.55) },
             highlight: { expr: rampColorExpr(t, 1.5) } };
  }

  function applyColor(prop, spec) {
    if (spec.expr) prop.expression = spec.expr;
    else prop.setValue(spec.value);
  }

  function sum(items) {
    var s = 0;
    for (var i = 0; i < items.length; i++) s += items[i].value;
    return s;
  }

  function maxVal(items) {
    var m = 0;
    for (var i = 0; i < items.length; i++) if (items[i].value > m) m = items[i].value;
    return m;
  }

  // =================================================== axes / grid / text

  /* Normalize bar/line/area data to {categories, series, overrides}.
   * Accepts the v2 shape (categories + series[]) or legacy items[]. */
  function normalizeSeries(cfg) {
    if (cfg.series && cfg.categories) {
      return {
        categories: cfg.categories,
        series: cfg.series,
        overrides: cfg.pointOverrides || []
      };
    }
    var cats = [], vals = [], ovr = [];
    for (var i = 0; i < cfg.items.length; i++) {
      cats.push(cfg.items[i].label);
      vals.push(cfg.items[i].value);
      ovr.push({ useCustom: !!cfg.items[i].useCustom, color: cfg.items[i].color });
    }
    return { categories: cats, series: [{ name: cfg.seriesName || "Series 1", values: vals }], overrides: ovr };
  }

  /* Value-axis range covering all series, negatives included, snapped to a
   * nice step and always spanning zero. */
  function computeAxis(seriesArr) {
    var maxV = 0, minV = 0;
    for (var j = 0; j < seriesArr.length; j++) {
      var vv = seriesArr[j].values;
      for (var i = 0; i < vv.length; i++) {
        if (vv[i] > maxV) maxV = vv[i];
        if (vv[i] < minV) minV = vv[i];
      }
    }
    if (maxV === 0 && minV === 0) maxV = 1;
    var step = niceStep(maxV - minV, 5);
    var niceMax = Math.ceil(maxV / step) * step;
    var niceMin = Math.floor(minV / step) * step;
    if (niceMax === niceMin) niceMax = niceMin + step;
    return { min: niceMin, max: niceMax, step: step, range: niceMax - niceMin };
  }

  function grandTotal(seriesArr) {
    var t = 0;
    for (var j = 0; j < seriesArr.length; j++) {
      for (var i = 0; i < seriesArr[j].values.length; i++) t += seriesArr[j].values[i];
    }
    return t === 0 ? 1 : t;
  }

  /* Color spec (fill/outline/highlight) for a series datum: per-point tones
   * in single-series mode (with per-point overrides), per-series tones when
   * there are multiple series. */
  function seriesColorSpec(data, i, j) {
    var m = data.series.length, n = data.categories.length;
    if (m === 1 && data.overrides[i] && data.overrides[i].useCustom) {
      var rgb = hexToRgb(data.overrides[i].color);
      return { fill: { value: [rgb[0], rgb[1], rgb[2], 1] },
               outline: { value: [rgb[0] * 0.55, rgb[1] * 0.55, rgb[2] * 0.55, 1] },
               highlight: { value: [Math.min(rgb[0] * 1.5 + 0.08, 1), Math.min(rgb[1] * 1.5 + 0.08, 1), Math.min(rgb[2] * 1.5 + 0.08, 1), 1] } };
    }
    var t = m > 1 ? itemTone(j, m) : itemTone(i, n);
    return { fill: { expr: rampColorExpr(t, 1) },
             outline: { expr: rampColorExpr(t, 0.55) },
             highlight: { expr: rampColorExpr(t, 1.5) } };
  }

  /* Gridlines, zero line, borders, and tick labels along the value axis.
   * horizontal=false → value axis is Y (ticks left); true → X (ticks below). */
  function buildValueAxis(comp, ctrl, geo, axis, fmt, total, horizontal) {
    var left = geo.left, right = geo.right, base = geo.base, top = geo.top, k = geo.k;

    var axes = addShapeItem(comp, ctrl, "Axes & Gridlines", LC.axes);
    axes.position.setValue([0, 0]);

    var ticks = Math.max(1, Math.round(axis.range / axis.step));
    var j, tv, cont, st;
    for (j = 0; j <= ticks; j++) {
      tv = axis.min + axis.step * j;
      var frac = (tv - axis.min) / axis.range;
      var pathPts = horizontal
        ? [[left + geo.pw * frac, top], [left + geo.pw * frac, base]]
        : [[left, base - geo.ph * frac], [right, base - geo.ph * frac]];
      var isZero = Math.abs(tv) < axis.step * 0.001;
      cont = addGroupWithPath(axes, (isZero ? "Zero Line " : "Gridline ") + formatStatic(tv, fmt, total), pathPts, false);
      st = addStroke(cont, (isZero ? 3 : 2) * k, labelColorExpr(), false);
      if (!isZero) st.property("ADBE Vector Stroke Opacity").setValue(22);
    }

    // Category-axis border.
    var borderPts = horizontal
      ? [[left, base], [left, top]]
      : [[left, base], [right, base]];
    cont = addGroupWithPath(axes, "Category Axis", borderPts, false);
    st = addStroke(cont, 2 * k, labelColorExpr(), false);
    st.property("ADBE Vector Stroke Opacity").setValue(60);

    axes.opacity.expression = staticFadeExpr(true, 100);

    // Tick value labels — the quietest tier of the type scale.
    for (j = 0; j <= ticks; j++) {
      tv = axis.min + axis.step * j;
      var frac2 = (tv - axis.min) / axis.range;
      var lab = addTextItem(comp, ctrl, "Tick — " + formatStatic(tv, fmt, total),
        formatStatic(tv, fmt, total), 22 * k,
        horizontal ? ParagraphJustification.CENTER_JUSTIFY : ParagraphJustification.RIGHT_JUSTIFY,
        "regular", LC.tick);
      if (horizontal) lab.position.setValue([left + geo.pw * frac2, base + 36 * k]);
      else lab.position.setValue([left - 16 * k, base - geo.ph * frac2 + 8 * k]);
      lab.opacity.expression = staticFadeExpr(true, 80);
    }
  }

  /* One swatch + name per series, laid out left-to-right above the plot. */
  function buildLegend(comp, ctrl, geo, data) {
    var k = geo.k;
    var m = data.series.length;
    var y = geo.top - 52 * k;
    var spacing = 260 * k;

    for (var j = m - 1; j >= 0; j--) {
      var x0 = geo.left + j * spacing;
      var tone = m > 1 ? itemTone(j, m) : 0;

      var swatch = addShapeItem(comp, ctrl, "Legend Swatch — \"" + data.series[j].name + "\"", LC.legend);
      swatch.position.setValue([x0 + 13 * k, y]);
      var grp = swatch.property("ADBE Root Vectors Group").addProperty("ADBE Vector Group");
      grp.name = "Swatch";
      var cont = grp.property("ADBE Vectors Group");
      var rect = cont.addProperty("ADBE Vector Shape - Rect");
      rect.property("ADBE Vector Rect Size").setValue([26 * k, 26 * k]);
      rect.property("ADBE Vector Rect Roundness").setValue(6 * k);
      var fill = cont.addProperty("ADBE Vector Graphic - Fill");
      fill.property("ADBE Vector Fill Color").expression = rampColorExpr(tone, 1);
      swatch.opacity.expression = staticFadeExpr(false, 100);

      var lab = addTextItem(comp, ctrl, "Legend — \"" + data.series[j].name + "\"",
        data.series[j].name, 26 * k, ParagraphJustification.LEFT_JUSTIFY, "medium", LC.legend);
      lab.position.setValue([x0 + 34 * k, y + 9 * k]);
      lab.opacity.expression = staticFadeExpr(false, 100);
    }
  }

  function buildTitle(comp, ctrl, cfg, x, y, k) {
    if (!cfg.title) return;
    var lab = addTextItem(comp, ctrl, "Chart Title — \"" + cfg.title + "\"",
      cfg.title, 54 * k, ParagraphJustification.CENTER_JUSTIFY, "bold", LC.title);
    lab.position.setValue([x, y]);
    lab.opacity.expression = staticFadeExpr(false, 100);
  }

  // ============================================================ bar chart

  /* One bar (tip cap + gradient body + outline + tone map + glow). Works
   * for both orientations and signed (negative) values. */
  function buildOneBar(comp, ctrl, name, pos, len, thick, horizontal, idx, colors, k) {
    var A = round3(Math.abs(len));
    var S = len < 0 ? -1 : 1;
    var capH = round3(12 * k);
    var bar = addShapeItem(comp, ctrl, name, LC.bar);
    bar.position.setValue(pos);

    // Bright cap riding the growing tip (added first = renders in front).
    // Its length is capped by the bar's own so nothing shows pre-build.
    var hgrp = bar.property("ADBE Root Vectors Group").addProperty("ADBE Vector Group");
    hgrp.name = "Tip Highlight";
    var hcont = hgrp.property("ADBE Vectors Group");
    var hrect = hcont.addProperty("ADBE Vector Shape - Rect");
    var capLen = 'Math.min(' + capH + ',' + A + '*e)';
    if (horizontal) {
      hrect.property("ADBE Vector Rect Size").expression =
        preamble(idx) + '[' + capLen + ',' + round3(thick * 0.9) + ']';
      hrect.property("ADBE Vector Rect Position").expression =
        preamble(idx) + '[' + S + '*(' + A + '*e-' + capLen + '/2),0]';
    } else {
      hrect.property("ADBE Vector Rect Size").expression =
        preamble(idx) + '[' + round3(thick * 0.9) + ',' + capLen + ']';
      hrect.property("ADBE Vector Rect Position").expression =
        preamble(idx) + '[0,' + (-S) + '*(' + A + '*e-' + capLen + '/2)]';
    }
    var hfill = hcont.addProperty("ADBE Vector Graphic - Fill");
    hfill.property("ADBE Vector Fill Color").setValue([1, 1, 1, 1]); // → Highlights tone via Tritone

    var grp = bar.property("ADBE Root Vectors Group").addProperty("ADBE Vector Group");
    grp.name = "Bar";
    var cont = grp.property("ADBE Vectors Group");
    var rect = cont.addProperty("ADBE Vector Shape - Rect");
    if (horizontal) {
      rect.property("ADBE Vector Rect Size").expression =
        preamble(idx) + '[Math.max(' + A + '*e,0),' + round3(thick) + ']';
      rect.property("ADBE Vector Rect Position").expression =
        preamble(idx) + '[' + S + '*Math.max(' + A + '*e,0)/2,0]';
    } else {
      rect.property("ADBE Vector Rect Size").expression =
        preamble(idx) + '[' + round3(thick) + ',Math.max(' + A + '*e,0)]';
      rect.property("ADBE Vector Rect Position").expression =
        preamble(idx) + '[0,' + (-S) + '*Math.max(' + A + '*e,0)/2]';
    }
    // White→black gradient toward the tip; Tritone supplies the live tones.
    var gfill = null;
    try {
      gfill = cont.addProperty("ADBE Vector Graphic - G-Fill");
      try { gfill.property("ADBE Vector Grad Type").setValue(1); } catch (eT) {} // linear
      gfill.property("ADBE Vector Grad Start Pt").expression = preamble(idx) +
        (horizontal ? '[' + S + '*Math.max(' + A + '*e,1),0]' : '[0,' + (-S) + '*Math.max(' + A + '*e,1)]');
      gfill.property("ADBE Vector Grad End Pt").setValue([0, 0]);
    } catch (eG) { gfill = null; }
    if (!gfill) { // very old AE — flat fill fallback
      var fill = cont.addProperty("ADBE Vector Graphic - Fill");
      applyColor(fill.property("ADBE Vector Fill Color"), colors.fill);
    }
    var st = cont.addProperty("ADBE Vector Graphic - Stroke");
    st.property("ADBE Vector Stroke Width").expression = outlineWidthExpr();
    st.property("ADBE Vector Stroke Color").setValue([0, 0, 0, 1]); // → Shadows tone via Tritone

    addTritoneFx(bar, colors);
    addGlowStack(bar, k, colors, true);
    return bar;
  }

  function buildBar(comp, ctrl, cfg, k) {
    var data = normalizeSeries(cfg);
    var n = data.categories.length;
    var m = data.series.length;
    var horiz = !!(cfg.bar && cfg.bar.horizontal);
    var pw = 1440 * k, ph = 700 * k;
    var geo = { pw: pw, ph: ph, left: -pw / 2, right: pw / 2, base: ph / 2, top: -ph / 2, k: k };

    var axis = computeAxis(data.series);
    var total = grandTotal(data.series);
    buildValueAxis(comp, ctrl, geo, axis, cfg.format, total, horiz);

    var showValues = !cfg.format || cfg.format.showValues !== false;
    var slot = (horiz ? ph : pw) / n;
    var groupLen = slot * (m > 1 ? 0.78 : 0.62);
    var thickSlot = groupLen / m;
    var thick = thickSlot * (m > 1 ? 0.88 : 1);
    var zeroFrac = (0 - axis.min) / axis.range;
    var zeroY = geo.base - ph * zeroFrac;
    var zeroX = geo.left + pw * zeroFrac;
    var vSize = horiz ? (m === 1 ? 40 : m === 2 ? 30 : 24) * k
                      : (m === 1 ? 72 : m === 2 ? 38 : 28) * k;

    var i, j, v, idx, colors;

    // Bars, series by series — tidy blocks in the timeline, 01 on top.
    // Stagger runs across categories with a small offset between series.
    for (j = m - 1; j >= 0; j--) {
      for (i = n - 1; i >= 0; i--) {
        v = data.series[j].values[i];
        idx = round3(i + j * 0.25);
        colors = seriesColorSpec(data, i, j);
        var name = "Bar " + pad2(i + 1) + (m > 1 ? "." + (j + 1) : "") + " — \"" + data.categories[i] + "\"" +
          (m > 1 ? " · " + data.series[j].name : "");
        var off = slot * (i + 0.5) - groupLen / 2 + thickSlot * (j + 0.5);
        if (horiz) {
          buildOneBar(comp, ctrl, name, [zeroX, geo.top + off], pw * v / axis.range, thick, true, idx, colors, k);
        } else {
          buildOneBar(comp, ctrl, name, [geo.left + off, zeroY], ph * v / axis.range, thick, false, idx, colors, k);
        }
      }
    }

    // Category labels — under the plot (vertical) / left of it (horizontal).
    for (i = n - 1; i >= 0; i--) {
      var clab = addTextItem(comp, ctrl, "Category " + pad2(i + 1) + " — \"" + data.categories[i] + "\"",
        data.categories[i], 27 * k,
        horiz ? ParagraphJustification.RIGHT_JUSTIFY : ParagraphJustification.CENTER_JUSTIFY,
        "medium", LC.category);
      if (horiz) clab.position.setValue([geo.left - 16 * k, geo.top + slot * (i + 0.5) + 8 * k]);
      else clab.position.setValue([geo.left + slot * (i + 0.5), geo.base + 44 * k]);
      clab.opacity.expression = preamble(i) + 'clamp(p*3,0,1)*Math.min(o,1)*100';
    }

    // Count-up value labels at each bar tip.
    if (showValues) {
      for (j = m - 1; j >= 0; j--) {
        for (i = n - 1; i >= 0; i--) {
          v = data.series[j].values[i];
          idx = round3(i + j * 0.25);
          var L = (horiz ? pw : ph) * v / axis.range;
          var A2 = round3(Math.abs(L));
          var S2 = L < 0 ? -1 : 1;
          var off2 = slot * (i + 0.5) - groupLen / 2 + thickSlot * (j + 0.5);
          var vname = "Value " + pad2(i + 1) + (m > 1 ? "." + (j + 1) : "") + " — \"" + data.categories[i] + "\"" +
            (m > 1 ? " · " + data.series[j].name : "");
          var just = horiz
            ? (S2 > 0 ? ParagraphJustification.LEFT_JUSTIFY : ParagraphJustification.RIGHT_JUSTIFY)
            : ParagraphJustification.CENTER_JUSTIFY;
          var vlab = addTextItem(comp, ctrl, vname, formatStatic(v, cfg.format, total), vSize, just, "bold", LC.value);
          if (horiz) {
            vlab.position.expression = preamble(idx) +
              '[' + round3(zeroX) + '+' + S2 + '*(Math.max(' + A2 + '*e,0)+' + round3(14 * k) + '),' +
              round3(geo.top + off2 + vSize * 0.35) + ']';
          } else {
            var tipOff = S2 > 0 ? -20 * k : (vSize * 0.9 + 8 * k);
            vlab.position.expression = preamble(idx) +
              '[' + round3(geo.left + off2) + ',' + round3(zeroY) + '+' + (-S2) + '*Math.max(' + A2 + '*e,0)+' + round3(tipOff) + ']';
          }
          vlab.property("ADBE Text Properties").property("ADBE Text Document").expression =
            preamble(idx) + countUpBody(v, total, cfg.format) + 'out';
          vlab.opacity.expression = preamble(idx) + 'clamp(p*4,0,1)*Math.min(o,1)*100';
        }
      }
    }

    buildLegend(comp, ctrl, geo, data);
    buildTitle(comp, ctrl, cfg, 0, geo.top - 110 * k, k);
    return geo;
  }

  // ====================================================== line/area chart

  /* Line chart; isArea=true renders the same geometry with a prominent
   * filled area (the Area chart type). Supports multiple series — each
   * series draws with its own tone, staggered by series index. */
  function buildLine(comp, ctrl, cfg, k, isArea) {
    var data = normalizeSeries(cfg);
    var n = data.categories.length;
    var m = data.series.length;
    var pw = 1440 * k, ph = 700 * k;
    var geo = { pw: pw, ph: ph, left: -pw / 2, right: pw / 2, base: ph / 2, top: -ph / 2, k: k };

    var axis = computeAxis(data.series);
    var total = grandTotal(data.series);
    buildValueAxis(comp, ctrl, geo, axis, cfg.format, total, false);

    var showValues = !cfg.format || cfg.format.showValues !== false;
    var zeroY = geo.base - ph * ((0 - axis.min) / axis.range);
    var pad = 50 * k;
    var usable = pw - pad * 2;
    var dotSize = (m > 1 ? 14 : 18) * k;
    var vSize = (m > 1 ? 26 : 34) * k;
    var areaOp = isArea ? (m > 1 ? 35 : 45) : (m > 1 ? 14 : 26);

    // Per-series point positions and draw-on length fractions.
    var i, j;
    var seriesPts = [], seriesFracs = [], seriesWins = [];
    for (j = 0; j < m; j++) {
      var pts = [];
      for (i = 0; i < n; i++) {
        var x = geo.left + pad + usable * (n > 1 ? i / (n - 1) : 0.5);
        var y = geo.base - ph * ((data.series[j].values[i] - axis.min) / axis.range);
        pts.push([x, y]);
      }
      var lens = [0], totalLen = 0;
      for (i = 1; i < n; i++) {
        var dx = pts[i][0] - pts[i - 1][0];
        var dy = pts[i][1] - pts[i - 1][1];
        totalLen += Math.sqrt(dx * dx + dy * dy);
        lens.push(totalLen);
      }
      var fracs = [], wins = [];
      for (i = 0; i < n; i++) {
        // Pop windows shrink near the path end so the last point always
        // completes its pop at exactly draw-on = 1.
        var f = totalLen > 0 ? Math.min(lens[i] / totalLen * 0.97, 0.97) : 0;
        fracs.push(f);
        wins.push(Math.max(0.001, Math.min(0.08, 1 - f)));
      }
      seriesPts.push(pts);
      seriesFracs.push(fracs);
      seriesWins.push(wins);
    }

    function popPre(j2, i2) {
      return preamble(j2) +
        'var pp=clamp((Math.min(e,1)-' + round6(seriesFracs[j2][i2]) + ')/' + round6(seriesWins[j2][i2]) + ',0,1);pp=pp*pp*(3-2*pp);\n';
    }

    function seriesTone(j2) { return m > 1 ? itemTone(j2, m) : 0; }

    // --- area fills (bottom block; the Area type just turns these up) ------
    for (j = m - 1; j >= 0; j--) {
      var pts2 = seriesPts[j];
      var apts = [];
      for (i = 0; i < n; i++) apts.push(pts2[i]);
      apts.push([pts2[n - 1][0], zeroY]);
      apts.push([pts2[0][0], zeroY]);
      var area = addShapeItem(comp, ctrl, "Area Fill — \"" + data.series[j].name + "\"", LC.area);
      area.position.setValue([0, 0]);
      var acont = addGroupWithPath(area, "Area", apts, true);
      var afill = acont.addProperty("ADBE Vector Graphic - Fill");
      afill.property("ADBE Vector Fill Color").expression = rampColorExpr(seriesTone(j), 1);
      area.opacity.expression = preamble(j) + 'Math.min(e,1)*' + areaOp;
      // Alpha fade toward the zero line (gradient opacity stops are not
      // scriptable — a heavily feathered Linear Wipe does the same job).
      try {
        var wipe = fxParade(area).addProperty("ADBE Linear Wipe");
        setFxValue(wipe, "ADBE Linear Wipe-0001", "Transition Completion", isArea ? 25 : 35);
        setFxValue(wipe, "ADBE Linear Wipe-0002", "Wipe Angle", 0);
        setFxValue(wipe, "ADBE Linear Wipe-0003", "Feather", 700 * k);
      } catch (eW) {}
    }

    // --- the lines ----------------------------------------------------------
    for (j = m - 1; j >= 0; j--) {
      var line = addShapeItem(comp, ctrl, "Chart Line — \"" + data.series[j].name + "\"", LC.line);
      line.position.setValue([0, 0]);
      var cont = addGroupWithPath(line, "Line", seriesPts[j], false);
      var trim = cont.addProperty("ADBE Vector Filter - Trim");
      trim.property("ADBE Vector Trim Start").setValue(0);
      trim.property("ADBE Vector Trim End").expression = preamble(j) + 'Math.min(e,1)*100';
      var st = cont.addProperty("ADBE Vector Graphic - Stroke");
      st.property("ADBE Vector Stroke Width").expression =
        'thisComp.layer("' + CTRL_NAME + '").effect("STYLE | Line Weight")(1)';
      st.property("ADBE Vector Stroke Color").expression = rampColorExpr(seriesTone(j), 1);
      try { st.property("ADBE Vector Stroke Line Cap").setValue(2); } catch (eCap) {} // round
      var lineColors = { fill: { expr: rampColorExpr(seriesTone(j), 1) }, highlight: { expr: rampColorExpr(seriesTone(j), 1.5) } };
      addGlowStack(line, k, lineColors, true);
    }

    // --- dots: glossy core with a tone ring, popping as the line arrives ----
    for (j = m - 1; j >= 0; j--) {
      for (i = n - 1; i >= 0; i--) {
        var colors = m > 1
          ? { fill: { expr: rampColorExpr(seriesTone(j), 1) },
              outline: { expr: rampColorExpr(seriesTone(j), 0.55) },
              highlight: { expr: rampColorExpr(seriesTone(j), 1.5) } }
          : seriesColorSpec(data, i, 0);
        var dname = "Point " + pad2(i + 1) + (m > 1 ? "." + (j + 1) : "") + " — \"" + data.categories[i] + "\"" +
          (m > 1 ? " · " + data.series[j].name : "");
        var dot = addShapeItem(comp, ctrl, dname, LC.dot);
        dot.position.setValue(seriesPts[j][i]);
        var dgrp = dot.property("ADBE Root Vectors Group").addProperty("ADBE Vector Group");
        dgrp.name = "Dot";
        var dcont = dgrp.property("ADBE Vectors Group");
        var ell = dcont.addProperty("ADBE Vector Shape - Ellipse");
        ell.property("ADBE Vector Ellipse Size").setValue([dotSize, dotSize]);
        var dfill = dcont.addProperty("ADBE Vector Graphic - Fill");
        applyColor(dfill.property("ADBE Vector Fill Color"), colors.highlight);
        var dst = dcont.addProperty("ADBE Vector Graphic - Stroke");
        dst.property("ADBE Vector Stroke Width").expression = outlineWidthExpr();
        applyColor(dst.property("ADBE Vector Stroke Color"), colors.fill);
        dot.scale.expression = popPre(j, i) +
          'var s=1.70158,u=pp-1;var eb=1+(s+1)*u*u*u+s*u*u;\n[100*eb,100*eb]';
        addGlowStack(dot, k, colors, false); // core tier only — many dots
      }
    }

    // --- category labels ------------------------------------------------------
    for (i = n - 1; i >= 0; i--) {
      var clab = addTextItem(comp, ctrl, "Category " + pad2(i + 1) + " — \"" + data.categories[i] + "\"",
        data.categories[i], 27 * k, ParagraphJustification.CENTER_JUSTIFY, "medium", LC.category);
      clab.position.setValue([seriesPts[0][i][0], geo.base + 44 * k]);
      clab.opacity.expression = popPre(0, i) + 'pp*100';
    }

    // --- value labels -----------------------------------------------------------
    if (showValues) {
      for (j = m - 1; j >= 0; j--) {
        for (i = n - 1; i >= 0; i--) {
          var v = data.series[j].values[i];
          var vname = "Value " + pad2(i + 1) + (m > 1 ? "." + (j + 1) : "") + " — \"" + data.categories[i] + "\"" +
            (m > 1 ? " · " + data.series[j].name : "");
          var vlab = addTextItem(comp, ctrl, vname,
            formatStatic(v, cfg.format, total), vSize, ParagraphJustification.CENTER_JUSTIFY, "bold", LC.value);
          vlab.position.setValue([seriesPts[j][i][0], seriesPts[j][i][1] - (dotSize + 18 * k)]);
          vlab.property("ADBE Text Properties").property("ADBE Text Document").expression =
            popPre(j, i) + countUpBody(v, total, cfg.format, "pp") + 'out';
          vlab.opacity.expression = popPre(j, i) + 'pp*100';
        }
      }
    }

    buildLegend(comp, ctrl, geo, data);
    buildTitle(comp, ctrl, cfg, 0, geo.top - 110 * k, k);
    return geo;
  }

  // ============================================================ pie chart

  /* Donut-aware slice geometry: the ring's midline diameter and stroke width
   * follow STYLE | Donut Hole % live (0 = solid pie, up to 92 = thin ring). */
  function donutSizeExpr(R) {
    return 'var C=thisComp.layer("' + CTRL_NAME + '");\n' +
      'var hh=clamp(C.effect("STYLE | Donut Hole %")(1)/100,0,0.92);\n' +
      'var d=' + round3(R) + '*(1+hh);\n[d,d]';
  }

  function donutWidthExpr(R) {
    return 'var C=thisComp.layer("' + CTRL_NAME + '");\n' +
      'var hh=clamp(C.effect("STYLE | Donut Hole %")(1)/100,0,0.92);\n' +
      round3(R) + '*(1-hh)';
  }

  /* Slices use the classic trim-path trick: a circle path of radius R/2 with
   * a stroke R wide fills the full disc; Trim Start/End carve the wedge.
   *
   * The reveal is ONE continuous radial sweep from 12 o'clock: a single
   * eased progress G (0..1 of the full circle, no per-slice stagger) drives
   * every slice, and each slice shows the clamped window [cum, cum+frac] of
   * G — so wedges grow adjacent to each other as the sweep passes through
   * them. Every slice layer's opacity is gated on the sweep reaching its
   * start angle, so nothing is visible before the animation begins. */
  function buildPie(comp, ctrl, cfg, k) {
    var R = 330 * k;
    var n = cfg.items.length;

    var order = [];
    var i;
    for (i = 0; i < n; i++) order.push(i);
    if (cfg.pie.sortDesc) {
      order.sort(function (a, b) { return cfg.items[b].value - cfg.items[a].value; });
    }

    var total = sum(cfg.items);
    var fracs = [];
    for (i = 0; i < n; i++) fracs.push(cfg.items[order[i]].value / total);

    var SWEEP = preamble(0) + 'var G=Math.min(e,1);\n';

    // Pre-compute label slots and resolve vertical collisions per side.
    var cum = 0;
    var slices = [];
    for (i = 0; i < n; i++) {
      var frac = fracs[i];
      var midT = cum + frac / 2;                 // 0..1 around the clock
      var theta = midT * 2 * Math.PI;            // from 12 o'clock, clockwise
      var dir = [Math.sin(theta), -Math.cos(theta)];
      slices.push({
        idx: order[i], frac: frac, cum: cum, dir: dir,
        side: dir[0] >= 0 ? 1 : -1,
        labelY: dir[1] * (R + 60 * k)
      });
      cum += frac;
    }
    // Labels are two lines tall (name + bold percent) — space accordingly.
    resolveLabelCollisions(slices, 1, 86 * k, R + 140 * k);
    resolveLabelCollisions(slices, -1, 86 * k, R + 140 * k);

    var rimW = 12 * k;

    // Layers are created bottom-up in organized blocks: slices, outline
    // ring, leader lines, then labels — tidy groups in the timeline, 01 at
    // the top of each block.
    for (i = n - 1; i >= 0; i--) {
      var s = slices[i];
      var it = cfg.items[s.idx];
      var colors = itemFillColorSpec(cfg, i, n);
      var pct = s.frac * 100;
      var niceName = "\"" + it.label + "\" (" + pct.toFixed(1) + "%)";
      var c0 = round6(s.cum);
      var c1 = round6(s.cum + s.frac);
      var trimEndExpr = SWEEP + 'clamp(G,' + c0 + ',' + c1 + ')*100';
      var gateExpr = SWEEP + '(G>' + c0 + ')?100:0';

      // --- slice -----------------------------------------------------------
      var slice = addShapeItem(comp, ctrl, "Pie Slice " + pad2(i + 1) + " — " + niceName, LC.slice);
      slice.position.setValue([0, 0]);

      // Bright rim along the outer edge (added first = renders in front),
      // swept with the slice — the glossy edge from the reference look.
      var rgrp2 = slice.property("ADBE Root Vectors Group").addProperty("ADBE Vector Group");
      rgrp2.name = "Rim Highlight";
      var rcont2 = rgrp2.property("ADBE Vectors Group");
      var rell2 = rcont2.addProperty("ADBE Vector Shape - Ellipse");
      rell2.property("ADBE Vector Ellipse Size").setValue([2 * R - rimW, 2 * R - rimW]);
      var rtrim2 = rcont2.addProperty("ADBE Vector Filter - Trim");
      rtrim2.property("ADBE Vector Trim Start").setValue(c0 * 100);
      rtrim2.property("ADBE Vector Trim End").expression = trimEndExpr;
      var rst2 = rcont2.addProperty("ADBE Vector Graphic - Stroke");
      rst2.property("ADBE Vector Stroke Width").setValue(rimW);
      rst2.property("ADBE Vector Stroke Color").setValue([1, 1, 1, 1]); // → Highlights tone via Tritone
      try { rst2.property("ADBE Vector Stroke Line Cap").setValue(1); } catch (eCap1) {}

      var grp = slice.property("ADBE Root Vectors Group").addProperty("ADBE Vector Group");
      grp.name = "Slice";
      var cont = grp.property("ADBE Vectors Group");
      var ell = cont.addProperty("ADBE Vector Shape - Ellipse");
      ell.property("ADBE Vector Ellipse Size").expression = donutSizeExpr(R); // donut-aware
      var trim = cont.addProperty("ADBE Vector Filter - Trim");
      trim.property("ADBE Vector Trim Start").setValue(c0 * 100);
      trim.property("ADBE Vector Trim End").expression = trimEndExpr;
      // Radial white→black gradient stroke (bright center, dark edge);
      // Tritone maps it to this slice's tones, live via the master color.
      var st = null;
      try {
        st = cont.addProperty("ADBE Vector Graphic - G-Stroke");
        try { st.property("ADBE Vector Grad Type").setValue(2); } catch (eT2) {} // radial
        try { st.property("ADBE Vector Grad Start Pt").setValue([0, 0]); } catch (eP1) {}
        try { st.property("ADBE Vector Grad End Pt").setValue([R, 0]); } catch (eP2) {}
      } catch (eGS) { st = null; }
      if (!st) { // very old AE — flat stroke fallback
        st = cont.addProperty("ADBE Vector Graphic - Stroke");
        applyColor(st.property("ADBE Vector Stroke Color"), colors.fill);
      }
      st.property("ADBE Vector Stroke Width").expression = donutWidthExpr(R); // donut-aware
      try { st.property("ADBE Vector Stroke Line Cap").setValue(1); } catch (eCap) {} // butt = radial edges

      // Hidden until the sweep reaches this slice — nothing pre-renders.
      slice.opacity.expression = gateExpr;
      addTritoneFx(slice, colors);
      addGlowStack(slice, k, colors, true);
    }

    // Darker outline ring around the pie's edge, drawn by the same sweep —
    // sits just above the slices in the stack.
    var ring = addShapeItem(comp, ctrl, "Pie Outline Ring", LC.ring);
    ring.position.setValue([0, 0]);
    var rgrp = ring.property("ADBE Root Vectors Group").addProperty("ADBE Vector Group");
    rgrp.name = "Ring";
    var rcont = rgrp.property("ADBE Vectors Group");
    var rell = rcont.addProperty("ADBE Vector Shape - Ellipse");
    rell.property("ADBE Vector Ellipse Size").setValue([R * 2, R * 2]);
    var rtrim = rcont.addProperty("ADBE Vector Filter - Trim");
    rtrim.property("ADBE Vector Trim Start").setValue(0);
    rtrim.property("ADBE Vector Trim End").expression = SWEEP + 'G*100';
    var rst = rcont.addProperty("ADBE Vector Graphic - Stroke");
    rst.property("ADBE Vector Stroke Width").expression = outlineWidthExpr();
    rst.property("ADBE Vector Stroke Color").expression = rampColorExpr(0, 0.55);
    ring.opacity.expression = SWEEP + '(G>0)?100:0';

    // Labels appear as the sweep crosses each slice's midpoint.
    function labelLP(sl) {
      var mid = round6(sl.cum + sl.frac / 2);
      var win = round6(Math.max(sl.frac / 2, 0.04));
      return SWEEP + 'var lp=clamp((G-' + mid + ')/' + win + ',0,1);lp=lp*lp*(3-2*lp);\n';
    }

    // --- leader lines (own block) -------------------------------------------
    for (i = n - 1; i >= 0; i--) {
      s = slices[i];
      it = cfg.items[s.idx];
      niceName = "\"" + it.label + "\" (" + (s.frac * 100).toFixed(1) + "%)";
      var LP = labelLP(s);
      var p0 = [s.dir[0] * (R - 4 * k), s.dir[1] * (R - 4 * k)];
      var p1 = [s.dir[0] * (R + 40 * k), s.dir[1] * (R + 40 * k)];
      var p2 = [s.side * (R + 120 * k), s.labelY];
      var leader = addShapeItem(comp, ctrl, "Leader " + pad2(i + 1) + " — " + niceName, LC.leader);
      leader.position.setValue([0, 0]);
      var lcont = addGroupWithPath(leader, "Leader", [p0, p1, p2], false);
      var ltrim = lcont.addProperty("ADBE Vector Filter - Trim");
      ltrim.property("ADBE Vector Trim Start").setValue(0);
      ltrim.property("ADBE Vector Trim End").expression = LP + 'lp*100';
      addStroke(lcont, 2 * k, labelColorExpr(), false);
    }

    // --- external labels: name (medium) over a bold count-up percent --------
    for (i = n - 1; i >= 0; i--) {
      s = slices[i];
      it = cfg.items[s.idx];
      pct = s.frac * 100;
      niceName = "\"" + it.label + "\" (" + pct.toFixed(1) + "%)";
      var LP2 = labelLP(s);
      var just = s.side > 0 ? ParagraphJustification.LEFT_JUSTIFY : ParagraphJustification.RIGHT_JUSTIFY;
      var labX = s.side * (R + 120 * k) + s.side * 14 * k;

      var nameLab = addTextItem(comp, ctrl, "Label " + pad2(i + 1) + " — " + niceName,
        it.label, 27 * k, just, "medium", LC.category);
      nameLab.position.setValue([labX, s.labelY + 2 * k]);
      nameLab.opacity.expression = LP2 + 'lp*100';

      var pctStatic = (cfg.pie.includeValue ? formatStaticNumber(it.value, cfg.format) + " · " : "") +
        pct.toFixed(1) + "%";
      var pctLab = addTextItem(comp, ctrl, "Value " + pad2(i + 1) + " — " + niceName,
        pctStatic, 36 * k, just, "bold", LC.value);
      pctLab.position.setValue([labX, s.labelY + 42 * k]);
      var valPart = cfg.pie.includeValue
        ? '"' + escStr(formatStaticNumber(it.value, cfg.format)) + ' · "'
        : '""';
      pctLab.property("ADBE Text Properties").property("ADBE Text Document").expression =
        LP2 + valPart + '+(' + round3(pct) + '*lp).toFixed(1)+"%"';
      pctLab.opacity.expression = LP2 + 'lp*100';
    }

    buildTitle(comp, ctrl, cfg, 0, -R - 130 * k, k);
    return { k: k, r: R };
  }

  function formatStaticNumber(v, fmt) {
    var s = v.toFixed(fmt.decimals);
    if (fmt.thousands) s = thousandsStr(s);
    return (fmt.prefix || "") + s + (fmt.suffix || "");
  }

  /* Push overlapping labels apart (top to bottom) on one side of the pie. */
  function resolveLabelCollisions(slices, side, minGap, maxY) {
    var group = [];
    var i;
    for (i = 0; i < slices.length; i++) {
      if (slices[i].side === side) group.push(slices[i]);
    }
    group.sort(function (a, b) { return a.labelY - b.labelY; });
    for (i = 1; i < group.length; i++) {
      if (group[i].labelY < group[i - 1].labelY + minGap) {
        group[i].labelY = group[i - 1].labelY + minGap;
      }
    }
    // If the stack ran past the bottom, shift the whole side back up.
    if (group.length > 0) {
      var overflow = group[group.length - 1].labelY - maxY;
      if (overflow > 0) {
        for (i = 0; i < group.length; i++) group[i].labelY -= overflow;
      }
    }
  }

  // ================================================================ entry

  function generate(jsonStr) {
    var undoOpen = false;
    try {
      var cfg = parseJSON(jsonStr);
      if (!cfg || !cfg.items || cfg.items.length < 2) return "ERR|Need at least 2 data points.";

      app.beginUndoGroup("Graphinator: Generate Chart");
      undoOpen = true;

      var comp = getComp();
      var k = Math.min(comp.width / 1920, comp.height / 1080);
      CHART_FONTS = resolveFonts();

      removeItems(comp);
      var res = ensureController(comp, cfg);
      var ctrl = res.ctrl;

      if (cfg.type === "bar") buildBar(comp, ctrl, cfg, k);
      else if (cfg.type === "line") buildLine(comp, ctrl, cfg, k, false);
      else if (cfg.type === "area") buildLine(comp, ctrl, cfg, k, true);
      else if (cfg.type === "pie") buildPie(comp, ctrl, cfg, k);
      else return "ERR|Unknown chart type: " + cfg.type;

      // Markers reflect the timing in force right now (live values if the
      // controller already existed). Refreshed on every Update.
      var anim = readAnimValues(ctrl, cfg);
      var startT = anim.delay;
      var nPts = cfg.categories ? cfg.categories.length : cfg.items.length;
      var mSer = cfg.series ? cfg.series.length : 1;
      var endT;
      if (cfg.type === "bar") endT = anim.delay + anim.duration + anim.stagger * ((nPts - 1) + (mSer - 1) * 0.25);
      else if (cfg.type === "line" || cfg.type === "area") endT = anim.delay + anim.duration + anim.stagger * (mSer - 1) + 0.3;
      else endT = anim.delay + anim.duration + 0.6; // pie: single sweep + label tail
      setMarkers(ctrl, startT, endT);

      storeData(ctrl, jsonStr);
      ctrl.moveToBeginning();

      // Leave the timeline tidy: nothing selected, all layers collapsed.
      for (var li = 1; li <= comp.numLayers; li++) {
        try { comp.layer(li).selected = false; } catch (eDesel) {}
      }

      app.endUndoGroup();
      undoOpen = false;

      var msg = "Built " + cfg.type + " chart with " + cfg.items.length + " points in \"" + comp.name + "\". " +
        (res.isNew
          ? "Colors, timing & scale are now live on the controller layer."
          : "Controller kept — your live color/timing tweaks were preserved.");
      return "OK|" + msg;
    } catch (err) {
      if (undoOpen) { try { app.endUndoGroup(); } catch (e2) {} }
      return "ERR|" + (err && err.message ? err.message : String(err)) + (err && err.line ? " (jsx line " + err.line + ")" : "");
    }
  }

  function readData() {
    try {
      var comp = app.project.activeItem;
      if (!(comp && comp instanceof CompItem)) return "ERR|Open the comp that contains a Graphinator chart first.";
      var ctrl = findController(comp);
      if (!ctrl) return "ERR|No \"" + CTRL_NAME + "\" layer found in this comp.";
      var c = String(ctrl.comment);
      var idx = c.indexOf(DATA_TAG);
      if (idx < 0) return "ERR|The controller has no stored chart data.";
      return "DATA|" + c.substring(idx + DATA_TAG.length);
    } catch (err) {
      return "ERR|" + (err && err.message ? err.message : String(err));
    }
  }

  // ================================================================= bake

  /* Convert the live expression rig to plain keyframes for fast playback and
   * rendering. Properties whose expressions don't reference time (colors,
   * widths, glow gains) freeze to their current value; time-driven ones are
   * sampled per frame across the build window (and the animate-out window)
   * and keyframed. Update rebuilds the live rig at any time. */
  function bakeProp(prop, layer, buildLen, outEn, outDur, step, stats) {
    var ex = "";
    try { ex = prop.expression; } catch (e) { return; }
    if (!ex || !prop.expressionEnabled) return;
    stats.props++;

    var refsTime = /(^|[^A-Za-z])(time|inPoint|outPoint)([^A-Za-z]|$)/.test(ex);
    if (!refsTime) {
      var v0 = prop.valueAtTime(layer.inPoint, false);
      prop.expression = "";
      try { prop.setValue(v0); } catch (eSet) {}
      return;
    }

    var t0 = layer.inPoint;
    var tEnd = Math.min(layer.outPoint, t0 + buildLen);
    var times = [];
    var t;
    for (t = t0; t <= tEnd + step / 2; t += step) times.push(Math.min(t, layer.outPoint));
    if (outEn) {
      var o0 = Math.max(layer.outPoint - outDur - 0.2, tEnd + step);
      for (t = o0; t <= layer.outPoint + step / 2; t += step) times.push(Math.min(t, layer.outPoint));
    }
    var vals = [];
    var i;
    for (i = 0; i < times.length; i++) vals.push(prop.valueAtTime(times[i], false));
    prop.expression = "";
    try {
      for (i = 0; i < times.length; i++) prop.setValueAtTime(times[i], vals[i]);
      stats.keys += times.length;
    } catch (eK) {}
  }

  function bakeGroup(group, layer, buildLen, outEn, outDur, step, stats) {
    for (var i = 1; i <= group.numProperties; i++) {
      var p = group.property(i);
      if (!p) continue;
      if (p.propertyType === PropertyType.PROPERTY) {
        bakeProp(p, layer, buildLen, outEn, outDur, step, stats);
      } else {
        bakeGroup(p, layer, buildLen, outEn, outDur, step, stats);
      }
    }
  }

  function bake() {
    var undoOpen = false;
    try {
      var comp = app.project.activeItem;
      if (!(comp && comp instanceof CompItem)) return "ERR|Open the comp that contains the chart first.";
      var ctrl = findController(comp);
      if (!ctrl) return "ERR|No Graphinator chart found in this comp.";

      app.beginUndoGroup("Graphinator: Bake to Keyframes");
      undoOpen = true;

      var fx = ctrl.property("ADBE Effect Parade");
      function fxVal(name, dflt) {
        try { return fx.property(name).property(1).value; } catch (e) { return dflt; }
      }
      var dly = fxVal("ANIM | Start Delay", 0.3);
      var dur = fxVal("ANIM | Build Duration", 2);
      var stag = fxVal("ANIM | Stagger", 0.25);
      var outEn = fxVal("ANIM | Out Enabled", 0) > 0;
      var outDur = fxVal("ANIM | Out Duration", 1);

      // Sample window covers the longest possible staggered build.
      var nGuess = 60;
      try {
        var c = String(ctrl.comment);
        var ix = c.indexOf(DATA_TAG);
        if (ix >= 0) {
          var stored = parseJSON(c.substring(ix + DATA_TAG.length));
          if (stored && stored.categories) nGuess = stored.categories.length;
          else if (stored && stored.items) nGuess = stored.items.length;
        }
      } catch (eN) {}
      var buildLen = dly + dur + stag * (nGuess + 1) + 1.0;
      var step = comp.frameDuration;
      var stats = { props: 0, keys: 0 };

      for (var i = comp.numLayers; i >= 1; i--) {
        var lay = comp.layer(i);
        if (String(lay.comment).indexOf(ITEM_TAG) !== 0) continue;
        bakeGroup(lay, lay, buildLen, outEn, outDur, step, stats);
      }

      app.endUndoGroup();
      undoOpen = false;
      return "OK|Baked " + stats.props + " expressions (" + stats.keys + " keyframes). The chart no longer follows the controller — press Update any time to rebuild the live rig.";
    } catch (err) {
      if (undoOpen) { try { app.endUndoGroup(); } catch (e2) {} }
      return "ERR|" + (err && err.message ? err.message : String(err));
    }
  }

  function setMasterColor(r, g, b) {
    try {
      var comp = app.project.activeItem;
      if (!(comp && comp instanceof CompItem)) return "ERR|No active comp.";
      var ctrl = findController(comp);
      if (!ctrl) return "ERR|No controller in this comp.";
      app.beginUndoGroup("Graphinator: Random Color");
      ctrl.property("ADBE Effect Parade").property("COLOR | Master Color").property(1)
        .setValue([r, g, b, 1]);
      app.endUndoGroup();
      return "OK|Master color updated.";
    } catch (err) {
      try { app.endUndoGroup(); } catch (e2) {}
      return "ERR|" + (err && err.message ? err.message : String(err));
    }
  }

  global.GRAPHINATOR = {
    generate: generate,
    readData: readData,
    setMasterColor: setMasterColor,
    bake: bake
  };

})($.global);
